/*
User Api Gateway REST API

Testing OldPortfolioControllerAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pubclient

import (
	"context"
	openapiclient "github.com/axylos/pub_client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_pubclient_OldPortfolioControllerAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OldPortfolioControllerAPIService GetPortfolio", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.OldPortfolioControllerAPI.GetPortfolio(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
