/*
User Api Gateway REST API

Testing PortfolioControllerAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pubclient

import (
	"context"
	openapiclient "github.com/axylos/pub_client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_pubclient_PortfolioControllerAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PortfolioControllerAPIService GetAccountPortfolio", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string

		resp, httpRes, err := apiClient.PortfolioControllerAPI.GetAccountPortfolio(context.Background(), accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PortfolioControllerAPIService GetAccountPortfolioV2", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string

		resp, httpRes, err := apiClient.PortfolioControllerAPI.GetAccountPortfolioV2(context.Background(), accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
