/*
User Api Gateway REST API

Testing InstrumentControllerAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pubclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_pubclient_InstrumentControllerAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InstrumentControllerAPIService GetAllInstruments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InstrumentControllerAPI.GetAllInstruments(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstrumentControllerAPIService GetInstrument", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var symbol string
		var type_ string

		resp, httpRes, err := apiClient.InstrumentControllerAPI.GetInstrument(context.Background(), symbol, type_).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
