/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type PortfolioControllerAPI interface {

	/*
	GetAccountPortfolio Method for GetAccountPortfolio

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param accountId
	@return PortfolioControllerAPIGetAccountPortfolioRequest
	*/
	GetAccountPortfolio(ctx context.Context, accountId string) PortfolioControllerAPIGetAccountPortfolioRequest

	// GetAccountPortfolioExecute executes the request
	//  @return ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount
	GetAccountPortfolioExecute(r PortfolioControllerAPIGetAccountPortfolioRequest) (*ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount, *http.Response, error)

	/*
	GetAccountPortfolioV2 Retrieve an account portfolio details snapshot

	Retrieves a snapshot of a specified account’s portfolio, including positions, equity breakdown, buying power, and open orders. Only non-IRA accounts are supported. The account must exist and belong to the authenticated client.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param accountId
	@return PortfolioControllerAPIGetAccountPortfolioV2Request
	*/
	GetAccountPortfolioV2(ctx context.Context, accountId string) PortfolioControllerAPIGetAccountPortfolioV2Request

	// GetAccountPortfolioV2Execute executes the request
	//  @return ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2
	GetAccountPortfolioV2Execute(r PortfolioControllerAPIGetAccountPortfolioV2Request) (*ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2, *http.Response, error)
}

// PortfolioControllerAPIService PortfolioControllerAPI service
type PortfolioControllerAPIService service

type PortfolioControllerAPIGetAccountPortfolioRequest struct {
	ctx context.Context
	ApiService PortfolioControllerAPI
	accountId string
}

func (r PortfolioControllerAPIGetAccountPortfolioRequest) Execute() (*ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount, *http.Response, error) {
	return r.ApiService.GetAccountPortfolioExecute(r)
}

/*
GetAccountPortfolio Method for GetAccountPortfolio

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param accountId
 @return PortfolioControllerAPIGetAccountPortfolioRequest
*/
func (a *PortfolioControllerAPIService) GetAccountPortfolio(ctx context.Context, accountId string) PortfolioControllerAPIGetAccountPortfolioRequest {
	return PortfolioControllerAPIGetAccountPortfolioRequest{
		ApiService: a,
		ctx: ctx,
		accountId: accountId,
	}
}

// Execute executes the request
//  @return ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount
func (a *PortfolioControllerAPIService) GetAccountPortfolioExecute(r PortfolioControllerAPIGetAccountPortfolioRequest) (*ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PortfolioControllerAPIService.GetAccountPortfolio")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/userapigateway/trading/{accountId}/portfolio"
	localVarPath = strings.Replace(localVarPath, "{"+"accountId"+"}", url.PathEscape(parameterValueToString(r.accountId, "accountId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.accountId) < 1 {
		return localVarReturnValue, nil, reportError("accountId must have at least 1 elements")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PortfolioControllerAPIGetAccountPortfolioV2Request struct {
	ctx context.Context
	ApiService PortfolioControllerAPI
	accountId string
}

func (r PortfolioControllerAPIGetAccountPortfolioV2Request) Execute() (*ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2, *http.Response, error) {
	return r.ApiService.GetAccountPortfolioV2Execute(r)
}

/*
GetAccountPortfolioV2 Retrieve an account portfolio details snapshot

Retrieves a snapshot of a specified account’s portfolio, including positions, equity breakdown, buying power, and open orders. Only non-IRA accounts are supported. The account must exist and belong to the authenticated client.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param accountId
 @return PortfolioControllerAPIGetAccountPortfolioV2Request
*/
func (a *PortfolioControllerAPIService) GetAccountPortfolioV2(ctx context.Context, accountId string) PortfolioControllerAPIGetAccountPortfolioV2Request {
	return PortfolioControllerAPIGetAccountPortfolioV2Request{
		ApiService: a,
		ctx: ctx,
		accountId: accountId,
	}
}

// Execute executes the request
//  @return ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2
func (a *PortfolioControllerAPIService) GetAccountPortfolioV2Execute(r PortfolioControllerAPIGetAccountPortfolioV2Request) (*ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PortfolioControllerAPIService.GetAccountPortfolioV2")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/userapigateway/trading/{accountId}/portfolio/v2"
	localVarPath = strings.Replace(localVarPath, "{"+"accountId"+"}", url.PathEscape(parameterValueToString(r.accountId, "accountId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.accountId) < 1 {
		return localVarReturnValue, nil, reportError("accountId must have at least 1 elements")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
