/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type UserControllerAPI interface {

	/*
	GetKycForUser Method for GetKycForUser

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return UserControllerAPIGetKycForUserRequest
	*/
	GetKycForUser(ctx context.Context) UserControllerAPIGetKycForUserRequest

	// GetKycForUserExecute executes the request
	//  @return ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse
	GetKycForUserExecute(r UserControllerAPIGetKycForUserRequest) (*ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse, *http.Response, error)
}

// UserControllerAPIService UserControllerAPI service
type UserControllerAPIService service

type UserControllerAPIGetKycForUserRequest struct {
	ctx context.Context
	ApiService UserControllerAPI
}

func (r UserControllerAPIGetKycForUserRequest) Execute() (*ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse, *http.Response, error) {
	return r.ApiService.GetKycForUserExecute(r)
}

/*
GetKycForUser Method for GetKycForUser

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return UserControllerAPIGetKycForUserRequest
*/
func (a *UserControllerAPIService) GetKycForUser(ctx context.Context) UserControllerAPIGetKycForUserRequest {
	return UserControllerAPIGetKycForUserRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse
func (a *UserControllerAPIService) GetKycForUserExecute(r UserControllerAPIGetKycForUserRequest) (*ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "UserControllerAPIService.GetKycForUser")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/userapigateway/user/kyc"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
