/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest{}

// ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest Used for multileg orders placed via the UserApiGatewayService or other service where the order is just a single request and the orderId is generated by the client
type ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest struct {
	// The OrderId, globally unique over time. This is also the deduplication key, if it is reused (on the same account) the operation is idempotent
	OrderId string `json:"orderId"`
	// The order quantity
	Quantity int32 `json:"quantity"`
	// The order type. Only LIMIT order are allowed
	Type string `json:"type"`
	// The limit price for the order. For debit spreads the limit price must be positive, for create spreads the limit price is negative
	LimitPrice string `json:"limitPrice"`
	Expiration ComHellopublicUserapigatewayApiRestOrderOrderExpiration `json:"expiration"`
	// From 2-6 legs. There can be at most 1 equity leg
	Legs []ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg `json:"legs"`
}

type _ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest

// NewComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest instantiates a new ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest(orderId string, quantity int32, type_ string, limitPrice string, expiration ComHellopublicUserapigatewayApiRestOrderOrderExpiration, legs []ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest {
	this := ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest{}
	this.OrderId = orderId
	this.Quantity = quantity
	this.Type = type_
	this.LimitPrice = limitPrice
	this.Expiration = expiration
	this.Legs = legs
	return &this
}

// NewComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequestWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequestWithDefaults() *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest {
	this := ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest{}
	return &this
}

// GetOrderId returns the OrderId field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) SetOrderId(v string) {
	o.OrderId = v
}

// GetQuantity returns the Quantity field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) SetQuantity(v int32) {
	o.Quantity = v
}

// GetType returns the Type field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) SetType(v string) {
	o.Type = v
}

// GetLimitPrice returns the LimitPrice field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) GetLimitPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LimitPrice
}

// GetLimitPriceOk returns a tuple with the LimitPrice field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) GetLimitPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LimitPrice, true
}

// SetLimitPrice sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) SetLimitPrice(v string) {
	o.LimitPrice = v
}

// GetExpiration returns the Expiration field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) GetExpiration() ComHellopublicUserapigatewayApiRestOrderOrderExpiration {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestOrderOrderExpiration
		return ret
	}

	return o.Expiration
}

// GetExpirationOk returns a tuple with the Expiration field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) GetExpirationOk() (*ComHellopublicUserapigatewayApiRestOrderOrderExpiration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expiration, true
}

// SetExpiration sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) SetExpiration(v ComHellopublicUserapigatewayApiRestOrderOrderExpiration) {
	o.Expiration = v
}

// GetLegs returns the Legs field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) GetLegs() []ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg {
	if o == nil {
		var ret []ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg
		return ret
	}

	return o.Legs
}

// GetLegsOk returns a tuple with the Legs field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) GetLegsOk() ([]ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg, bool) {
	if o == nil {
		return nil, false
	}
	return o.Legs, true
}

// SetLegs sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) SetLegs(v []ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) {
	o.Legs = v
}

func (o ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["orderId"] = o.OrderId
	toSerialize["quantity"] = o.Quantity
	toSerialize["type"] = o.Type
	toSerialize["limitPrice"] = o.LimitPrice
	toSerialize["expiration"] = o.Expiration
	toSerialize["legs"] = o.Legs
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"orderId",
		"quantity",
		"type",
		"limitPrice",
		"expiration",
		"legs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest := _ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest(varComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest)

	return err
}

type NullableComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest struct {
	value *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) Get() *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) Set(val *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest(val *ComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) *NullableComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest {
	return &NullableComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderApiMultilegOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


