/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2{}

// ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 Portfolio equity summary
type ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 struct {
	// Type of asset.
	Type string `json:"type"`
	// Total value for the given asset type.
	Value string `json:"value"`
	// The percentage of the portfolio this asset type constitutes.                               The percentage number is given with 2 decimals.
	PercentageOfPortfolio *string `json:"percentageOfPortfolio,omitempty"`
}

type _ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 instantiates a new ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2(type_ string, value string) *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 {
	this := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2{}
	this.Type = type_
	this.Value = value
	return &this
}

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2WithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2WithDefaults() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 {
	this := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2{}
	return &this
}

// GetType returns the Type field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) SetValue(v string) {
	o.Value = v
}

// GetPercentageOfPortfolio returns the PercentageOfPortfolio field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) GetPercentageOfPortfolio() string {
	if o == nil || IsNil(o.PercentageOfPortfolio) {
		var ret string
		return ret
	}
	return *o.PercentageOfPortfolio
}

// GetPercentageOfPortfolioOk returns a tuple with the PercentageOfPortfolio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) GetPercentageOfPortfolioOk() (*string, bool) {
	if o == nil || IsNil(o.PercentageOfPortfolio) {
		return nil, false
	}
	return o.PercentageOfPortfolio, true
}

// HasPercentageOfPortfolio returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) HasPercentageOfPortfolio() bool {
	if o != nil && !IsNil(o.PercentageOfPortfolio) {
		return true
	}

	return false
}

// SetPercentageOfPortfolio gets a reference to the given string and assigns it to the PercentageOfPortfolio field.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) SetPercentageOfPortfolio(v string) {
	o.PercentageOfPortfolio = &v
}

func (o ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["value"] = o.Value
	if !IsNil(o.PercentageOfPortfolio) {
		toSerialize["percentageOfPortfolio"] = o.PercentageOfPortfolio
	}
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 := _ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2(varComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2)

	return err
}

type NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 struct {
	value *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) Get() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) Set(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 {
	return &NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


