/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse{}

// ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse struct for ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse
type ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse struct {
	Person ComHellopublicUserapigatewayApiRestUserPersonInfo `json:"person"`
	Accounts []ComHellopublicUserapigatewayApiRestUserAccountKyc `json:"accounts,omitempty"`
}

type _ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse

// NewComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse instantiates a new ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse(person ComHellopublicUserapigatewayApiRestUserPersonInfo) *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse {
	this := ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse{}
	this.Person = person
	return &this
}

// NewComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponseWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponseWithDefaults() *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse {
	this := ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse{}
	return &this
}

// GetPerson returns the Person field value
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) GetPerson() ComHellopublicUserapigatewayApiRestUserPersonInfo {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestUserPersonInfo
		return ret
	}

	return o.Person
}

// GetPersonOk returns a tuple with the Person field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) GetPersonOk() (*ComHellopublicUserapigatewayApiRestUserPersonInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Person, true
}

// SetPerson sets field value
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) SetPerson(v ComHellopublicUserapigatewayApiRestUserPersonInfo) {
	o.Person = v
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) GetAccounts() []ComHellopublicUserapigatewayApiRestUserAccountKyc {
	if o == nil || IsNil(o.Accounts) {
		var ret []ComHellopublicUserapigatewayApiRestUserAccountKyc
		return ret
	}
	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) GetAccountsOk() ([]ComHellopublicUserapigatewayApiRestUserAccountKyc, bool) {
	if o == nil || IsNil(o.Accounts) {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) HasAccounts() bool {
	if o != nil && !IsNil(o.Accounts) {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []ComHellopublicUserapigatewayApiRestUserAccountKyc and assigns it to the Accounts field.
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) SetAccounts(v []ComHellopublicUserapigatewayApiRestUserAccountKyc) {
	o.Accounts = v
}

func (o ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["person"] = o.Person
	if !IsNil(o.Accounts) {
		toSerialize["accounts"] = o.Accounts
	}
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"person",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse := _ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse(varComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse)

	return err
}

type NullableComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse struct {
	value *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) Get() *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) Set(val *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse(val *ComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) *NullableComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse {
	return &NullableComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestUserPersonInfoWithAccountKycResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


