/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
)

// checks if the ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement{}

// ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement Price increment information for option orders.
type ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement struct {
	IncrementBelow3 *string `json:"incrementBelow3,omitempty"`
	IncrementAbove3 *string `json:"incrementAbove3,omitempty"`
	CurrentIncrement *string `json:"currentIncrement,omitempty"`
}

// NewComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement instantiates a new ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement() *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement {
	this := ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement{}
	return &this
}

// NewComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrementWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrementWithDefaults() *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement {
	this := ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement{}
	return &this
}

// GetIncrementBelow3 returns the IncrementBelow3 field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) GetIncrementBelow3() string {
	if o == nil || IsNil(o.IncrementBelow3) {
		var ret string
		return ret
	}
	return *o.IncrementBelow3
}

// GetIncrementBelow3Ok returns a tuple with the IncrementBelow3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) GetIncrementBelow3Ok() (*string, bool) {
	if o == nil || IsNil(o.IncrementBelow3) {
		return nil, false
	}
	return o.IncrementBelow3, true
}

// HasIncrementBelow3 returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) HasIncrementBelow3() bool {
	if o != nil && !IsNil(o.IncrementBelow3) {
		return true
	}

	return false
}

// SetIncrementBelow3 gets a reference to the given string and assigns it to the IncrementBelow3 field.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) SetIncrementBelow3(v string) {
	o.IncrementBelow3 = &v
}

// GetIncrementAbove3 returns the IncrementAbove3 field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) GetIncrementAbove3() string {
	if o == nil || IsNil(o.IncrementAbove3) {
		var ret string
		return ret
	}
	return *o.IncrementAbove3
}

// GetIncrementAbove3Ok returns a tuple with the IncrementAbove3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) GetIncrementAbove3Ok() (*string, bool) {
	if o == nil || IsNil(o.IncrementAbove3) {
		return nil, false
	}
	return o.IncrementAbove3, true
}

// HasIncrementAbove3 returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) HasIncrementAbove3() bool {
	if o != nil && !IsNil(o.IncrementAbove3) {
		return true
	}

	return false
}

// SetIncrementAbove3 gets a reference to the given string and assigns it to the IncrementAbove3 field.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) SetIncrementAbove3(v string) {
	o.IncrementAbove3 = &v
}

// GetCurrentIncrement returns the CurrentIncrement field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) GetCurrentIncrement() string {
	if o == nil || IsNil(o.CurrentIncrement) {
		var ret string
		return ret
	}
	return *o.CurrentIncrement
}

// GetCurrentIncrementOk returns a tuple with the CurrentIncrement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) GetCurrentIncrementOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentIncrement) {
		return nil, false
	}
	return o.CurrentIncrement, true
}

// HasCurrentIncrement returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) HasCurrentIncrement() bool {
	if o != nil && !IsNil(o.CurrentIncrement) {
		return true
	}

	return false
}

// SetCurrentIncrement gets a reference to the given string and assigns it to the CurrentIncrement field.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) SetCurrentIncrement(v string) {
	o.CurrentIncrement = &v
}

func (o ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IncrementBelow3) {
		toSerialize["incrementBelow3"] = o.IncrementBelow3
	}
	if !IsNil(o.IncrementAbove3) {
		toSerialize["incrementAbove3"] = o.IncrementAbove3
	}
	if !IsNil(o.CurrentIncrement) {
		toSerialize["currentIncrement"] = o.CurrentIncrement
	}
	return toSerialize, nil
}

type NullableComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement struct {
	value *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) Get() *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) Set(val *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement(val *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) *NullableComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement {
	return &NullableComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


