/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions the model 'ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions'
type ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions string

// List of com_hellopublic_userapigateway_api_rest_account_AccountSettings_tradePermissions
const (
	BUY_AND_SELL ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions = "BUY_AND_SELL"
	RESTRICTED_SETTLED_FUNDS_ONLY ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions = "RESTRICTED_SETTLED_FUNDS_ONLY"
	RESTRICTED_CLOSE_ONLY ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions = "RESTRICTED_CLOSE_ONLY"
	RESTRICTED_NO_TRADING ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions = "RESTRICTED_NO_TRADING"
)

// All allowed values of ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions enum
var AllowedComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissionsEnumValues = []ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions{
	"BUY_AND_SELL",
	"RESTRICTED_SETTLED_FUNDS_ONLY",
	"RESTRICTED_CLOSE_ONLY",
	"RESTRICTED_NO_TRADING",
}

func (v *ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissionsEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions", value)
}

// NewComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissionsFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissionsFromValue(v string) (*ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions, error) {
	ev := ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissionsEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissionsEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_account_AccountSettings_tradePermissions value
func (v ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions) Ptr() *ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions struct {
	value *ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions) Get() *ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions) Set(val *ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions(val *ComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions) *NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions {
	return &NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsTradePermissions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

