/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
)

// checks if the ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse{}

// ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse struct for ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse
type ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse struct {
	// The base symbol for which the option expirations belong.
	BaseSymbol *string `json:"baseSymbol,omitempty"`
	// List of option expirations for the given symbol.
	Expirations []string `json:"expirations,omitempty"`
}

// NewComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse instantiates a new ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse() *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse {
	this := ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse{}
	return &this
}

// NewComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponseWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponseWithDefaults() *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse {
	this := ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse{}
	return &this
}

// GetBaseSymbol returns the BaseSymbol field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) GetBaseSymbol() string {
	if o == nil || IsNil(o.BaseSymbol) {
		var ret string
		return ret
	}
	return *o.BaseSymbol
}

// GetBaseSymbolOk returns a tuple with the BaseSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) GetBaseSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.BaseSymbol) {
		return nil, false
	}
	return o.BaseSymbol, true
}

// HasBaseSymbol returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) HasBaseSymbol() bool {
	if o != nil && !IsNil(o.BaseSymbol) {
		return true
	}

	return false
}

// SetBaseSymbol gets a reference to the given string and assigns it to the BaseSymbol field.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) SetBaseSymbol(v string) {
	o.BaseSymbol = &v
}

// GetExpirations returns the Expirations field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) GetExpirations() []string {
	if o == nil || IsNil(o.Expirations) {
		var ret []string
		return ret
	}
	return o.Expirations
}

// GetExpirationsOk returns a tuple with the Expirations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) GetExpirationsOk() ([]string, bool) {
	if o == nil || IsNil(o.Expirations) {
		return nil, false
	}
	return o.Expirations, true
}

// HasExpirations returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) HasExpirations() bool {
	if o != nil && !IsNil(o.Expirations) {
		return true
	}

	return false
}

// SetExpirations gets a reference to the given []string and assigns it to the Expirations field.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) SetExpirations(v []string) {
	o.Expirations = v
}

func (o ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BaseSymbol) {
		toSerialize["baseSymbol"] = o.BaseSymbol
	}
	if !IsNil(o.Expirations) {
		toSerialize["expirations"] = o.Expirations
	}
	return toSerialize, nil
}

type NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse struct {
	value *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) Get() *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) Set(val *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse(val *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) *NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse {
	return &NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionExpirationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


