/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestUserPersonInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestUserPersonInfo{}

// ComHellopublicUserapigatewayApiRestUserPersonInfo struct for ComHellopublicUserapigatewayApiRestUserPersonInfo
type ComHellopublicUserapigatewayApiRestUserPersonInfo struct {
	Name ComHellopublicUserapigatewayApiRestUserPersonInfoName `json:"name"`
	Address ComHellopublicUserapigatewayApiRestUserPersonInfoAddress `json:"address"`
	DateOfBirth string `json:"dateOfBirth"`
}

type _ComHellopublicUserapigatewayApiRestUserPersonInfo ComHellopublicUserapigatewayApiRestUserPersonInfo

// NewComHellopublicUserapigatewayApiRestUserPersonInfo instantiates a new ComHellopublicUserapigatewayApiRestUserPersonInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestUserPersonInfo(name ComHellopublicUserapigatewayApiRestUserPersonInfoName, address ComHellopublicUserapigatewayApiRestUserPersonInfoAddress, dateOfBirth string) *ComHellopublicUserapigatewayApiRestUserPersonInfo {
	this := ComHellopublicUserapigatewayApiRestUserPersonInfo{}
	this.Name = name
	this.Address = address
	this.DateOfBirth = dateOfBirth
	return &this
}

// NewComHellopublicUserapigatewayApiRestUserPersonInfoWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestUserPersonInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestUserPersonInfoWithDefaults() *ComHellopublicUserapigatewayApiRestUserPersonInfo {
	this := ComHellopublicUserapigatewayApiRestUserPersonInfo{}
	return &this
}

// GetName returns the Name field value
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfo) GetName() ComHellopublicUserapigatewayApiRestUserPersonInfoName {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestUserPersonInfoName
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfo) GetNameOk() (*ComHellopublicUserapigatewayApiRestUserPersonInfoName, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfo) SetName(v ComHellopublicUserapigatewayApiRestUserPersonInfoName) {
	o.Name = v
}

// GetAddress returns the Address field value
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfo) GetAddress() ComHellopublicUserapigatewayApiRestUserPersonInfoAddress {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestUserPersonInfoAddress
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfo) GetAddressOk() (*ComHellopublicUserapigatewayApiRestUserPersonInfoAddress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfo) SetAddress(v ComHellopublicUserapigatewayApiRestUserPersonInfoAddress) {
	o.Address = v
}

// GetDateOfBirth returns the DateOfBirth field value
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfo) GetDateOfBirth() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DateOfBirth
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfo) GetDateOfBirthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DateOfBirth, true
}

// SetDateOfBirth sets field value
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfo) SetDateOfBirth(v string) {
	o.DateOfBirth = v
}

func (o ComHellopublicUserapigatewayApiRestUserPersonInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestUserPersonInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["address"] = o.Address
	toSerialize["dateOfBirth"] = o.DateOfBirth
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestUserPersonInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"address",
		"dateOfBirth",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestUserPersonInfo := _ComHellopublicUserapigatewayApiRestUserPersonInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestUserPersonInfo)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestUserPersonInfo(varComHellopublicUserapigatewayApiRestUserPersonInfo)

	return err
}

type NullableComHellopublicUserapigatewayApiRestUserPersonInfo struct {
	value *ComHellopublicUserapigatewayApiRestUserPersonInfo
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestUserPersonInfo) Get() *ComHellopublicUserapigatewayApiRestUserPersonInfo {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestUserPersonInfo) Set(val *ComHellopublicUserapigatewayApiRestUserPersonInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestUserPersonInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestUserPersonInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestUserPersonInfo(val *ComHellopublicUserapigatewayApiRestUserPersonInfo) *NullableComHellopublicUserapigatewayApiRestUserPersonInfo {
	return &NullableComHellopublicUserapigatewayApiRestUserPersonInfo{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestUserPersonInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestUserPersonInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


