/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse{}

// ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse # PreflightSingleLegResponse Response containing estimated costs, fees, and other information needed before placing a single-leg order.  ## Fields  ### Instrument Information - **symbol** - The trading symbol for the instrument - **cusip** - The CUSIP identifier for the instrument (if applicable) - **securityType** - The type of security (EQUITY, OPTION, BOND, etc.) - **rootSymbol** - The root symbol for options and other derivatives - **rootOptionSymbol** - The root option symbol for option chains  ### Cost and Fee Information - **estimatedCommission** - The estimated commission amount that will be charged if the order executes - **regulatoryFees** - Gateway regulatory fees breakdown including SEC, TAF, ORF, OCC, CAT fees - **estimatedCost** - The total estimated cost including all fees and commissions - **buyingPowerRequirement** - The buying power required for this order  ### Order Details - **orderValue** - The estimated order value, excluding fees and commission - **estimatedQuantity** - For quantity orders this is exact, for amount-based orders this is an estimate - **estimatedProceeds** - The estimated proceeds from the order (for sell orders)  ### Option-Specific Information - **optionDetails** - Consolidated option-specific details including strike price, expiration, rebates, and fees - **priceIncrement** - Price increment information for option orders
type ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse struct {
	Instrument ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument `json:"instrument"`
	Cusip *string `json:"cusip,omitempty"`
	RootSymbol *string `json:"rootSymbol,omitempty"`
	RootOptionSymbol *string `json:"rootOptionSymbol,omitempty"`
	EstimatedCommission *string `json:"estimatedCommission,omitempty"`
	RegulatoryFees *ComHellopublicUserapigatewayApiRestPreflightGatewayRegulatoryFees `json:"regulatoryFees,omitempty"`
	EstimatedIndexOptionFee *string `json:"estimatedIndexOptionFee,omitempty"`
	OrderValue string `json:"orderValue"`
	EstimatedQuantity *string `json:"estimatedQuantity,omitempty"`
	EstimatedCost *string `json:"estimatedCost,omitempty"`
	BuyingPowerRequirement *string `json:"buyingPowerRequirement,omitempty"`
	EstimatedProceeds *string `json:"estimatedProceeds,omitempty"`
	OptionDetails *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionDetails `json:"optionDetails,omitempty"`
	EstimatedOrderRebate *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate `json:"estimatedOrderRebate,omitempty"`
	MarginRequirement *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement `json:"marginRequirement,omitempty"`
	MarginImpact *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact `json:"marginImpact,omitempty"`
	PriceIncrement *ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement `json:"priceIncrement,omitempty"`
}

type _ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse

// NewComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse instantiates a new ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse(instrument ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument, orderValue string) *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse {
	this := ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse{}
	this.Instrument = instrument
	this.OrderValue = orderValue
	return &this
}

// NewComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponseWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponseWithDefaults() *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse {
	this := ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse{}
	return &this
}

// GetInstrument returns the Instrument field value
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetInstrument() ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument
		return ret
	}

	return o.Instrument
}

// GetInstrumentOk returns a tuple with the Instrument field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetInstrumentOk() (*ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instrument, true
}

// SetInstrument sets field value
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetInstrument(v ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) {
	o.Instrument = v
}

// GetCusip returns the Cusip field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetCusip() string {
	if o == nil || IsNil(o.Cusip) {
		var ret string
		return ret
	}
	return *o.Cusip
}

// GetCusipOk returns a tuple with the Cusip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetCusipOk() (*string, bool) {
	if o == nil || IsNil(o.Cusip) {
		return nil, false
	}
	return o.Cusip, true
}

// HasCusip returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasCusip() bool {
	if o != nil && !IsNil(o.Cusip) {
		return true
	}

	return false
}

// SetCusip gets a reference to the given string and assigns it to the Cusip field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetCusip(v string) {
	o.Cusip = &v
}

// GetRootSymbol returns the RootSymbol field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetRootSymbol() string {
	if o == nil || IsNil(o.RootSymbol) {
		var ret string
		return ret
	}
	return *o.RootSymbol
}

// GetRootSymbolOk returns a tuple with the RootSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetRootSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.RootSymbol) {
		return nil, false
	}
	return o.RootSymbol, true
}

// HasRootSymbol returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasRootSymbol() bool {
	if o != nil && !IsNil(o.RootSymbol) {
		return true
	}

	return false
}

// SetRootSymbol gets a reference to the given string and assigns it to the RootSymbol field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetRootSymbol(v string) {
	o.RootSymbol = &v
}

// GetRootOptionSymbol returns the RootOptionSymbol field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetRootOptionSymbol() string {
	if o == nil || IsNil(o.RootOptionSymbol) {
		var ret string
		return ret
	}
	return *o.RootOptionSymbol
}

// GetRootOptionSymbolOk returns a tuple with the RootOptionSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetRootOptionSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.RootOptionSymbol) {
		return nil, false
	}
	return o.RootOptionSymbol, true
}

// HasRootOptionSymbol returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasRootOptionSymbol() bool {
	if o != nil && !IsNil(o.RootOptionSymbol) {
		return true
	}

	return false
}

// SetRootOptionSymbol gets a reference to the given string and assigns it to the RootOptionSymbol field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetRootOptionSymbol(v string) {
	o.RootOptionSymbol = &v
}

// GetEstimatedCommission returns the EstimatedCommission field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetEstimatedCommission() string {
	if o == nil || IsNil(o.EstimatedCommission) {
		var ret string
		return ret
	}
	return *o.EstimatedCommission
}

// GetEstimatedCommissionOk returns a tuple with the EstimatedCommission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetEstimatedCommissionOk() (*string, bool) {
	if o == nil || IsNil(o.EstimatedCommission) {
		return nil, false
	}
	return o.EstimatedCommission, true
}

// HasEstimatedCommission returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasEstimatedCommission() bool {
	if o != nil && !IsNil(o.EstimatedCommission) {
		return true
	}

	return false
}

// SetEstimatedCommission gets a reference to the given string and assigns it to the EstimatedCommission field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetEstimatedCommission(v string) {
	o.EstimatedCommission = &v
}

// GetRegulatoryFees returns the RegulatoryFees field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetRegulatoryFees() ComHellopublicUserapigatewayApiRestPreflightGatewayRegulatoryFees {
	if o == nil || IsNil(o.RegulatoryFees) {
		var ret ComHellopublicUserapigatewayApiRestPreflightGatewayRegulatoryFees
		return ret
	}
	return *o.RegulatoryFees
}

// GetRegulatoryFeesOk returns a tuple with the RegulatoryFees field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetRegulatoryFeesOk() (*ComHellopublicUserapigatewayApiRestPreflightGatewayRegulatoryFees, bool) {
	if o == nil || IsNil(o.RegulatoryFees) {
		return nil, false
	}
	return o.RegulatoryFees, true
}

// HasRegulatoryFees returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasRegulatoryFees() bool {
	if o != nil && !IsNil(o.RegulatoryFees) {
		return true
	}

	return false
}

// SetRegulatoryFees gets a reference to the given ComHellopublicUserapigatewayApiRestPreflightGatewayRegulatoryFees and assigns it to the RegulatoryFees field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetRegulatoryFees(v ComHellopublicUserapigatewayApiRestPreflightGatewayRegulatoryFees) {
	o.RegulatoryFees = &v
}

// GetEstimatedIndexOptionFee returns the EstimatedIndexOptionFee field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetEstimatedIndexOptionFee() string {
	if o == nil || IsNil(o.EstimatedIndexOptionFee) {
		var ret string
		return ret
	}
	return *o.EstimatedIndexOptionFee
}

// GetEstimatedIndexOptionFeeOk returns a tuple with the EstimatedIndexOptionFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetEstimatedIndexOptionFeeOk() (*string, bool) {
	if o == nil || IsNil(o.EstimatedIndexOptionFee) {
		return nil, false
	}
	return o.EstimatedIndexOptionFee, true
}

// HasEstimatedIndexOptionFee returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasEstimatedIndexOptionFee() bool {
	if o != nil && !IsNil(o.EstimatedIndexOptionFee) {
		return true
	}

	return false
}

// SetEstimatedIndexOptionFee gets a reference to the given string and assigns it to the EstimatedIndexOptionFee field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetEstimatedIndexOptionFee(v string) {
	o.EstimatedIndexOptionFee = &v
}

// GetOrderValue returns the OrderValue field value
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetOrderValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderValue
}

// GetOrderValueOk returns a tuple with the OrderValue field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetOrderValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderValue, true
}

// SetOrderValue sets field value
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetOrderValue(v string) {
	o.OrderValue = v
}

// GetEstimatedQuantity returns the EstimatedQuantity field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetEstimatedQuantity() string {
	if o == nil || IsNil(o.EstimatedQuantity) {
		var ret string
		return ret
	}
	return *o.EstimatedQuantity
}

// GetEstimatedQuantityOk returns a tuple with the EstimatedQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetEstimatedQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.EstimatedQuantity) {
		return nil, false
	}
	return o.EstimatedQuantity, true
}

// HasEstimatedQuantity returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasEstimatedQuantity() bool {
	if o != nil && !IsNil(o.EstimatedQuantity) {
		return true
	}

	return false
}

// SetEstimatedQuantity gets a reference to the given string and assigns it to the EstimatedQuantity field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetEstimatedQuantity(v string) {
	o.EstimatedQuantity = &v
}

// GetEstimatedCost returns the EstimatedCost field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetEstimatedCost() string {
	if o == nil || IsNil(o.EstimatedCost) {
		var ret string
		return ret
	}
	return *o.EstimatedCost
}

// GetEstimatedCostOk returns a tuple with the EstimatedCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetEstimatedCostOk() (*string, bool) {
	if o == nil || IsNil(o.EstimatedCost) {
		return nil, false
	}
	return o.EstimatedCost, true
}

// HasEstimatedCost returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasEstimatedCost() bool {
	if o != nil && !IsNil(o.EstimatedCost) {
		return true
	}

	return false
}

// SetEstimatedCost gets a reference to the given string and assigns it to the EstimatedCost field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetEstimatedCost(v string) {
	o.EstimatedCost = &v
}

// GetBuyingPowerRequirement returns the BuyingPowerRequirement field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetBuyingPowerRequirement() string {
	if o == nil || IsNil(o.BuyingPowerRequirement) {
		var ret string
		return ret
	}
	return *o.BuyingPowerRequirement
}

// GetBuyingPowerRequirementOk returns a tuple with the BuyingPowerRequirement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetBuyingPowerRequirementOk() (*string, bool) {
	if o == nil || IsNil(o.BuyingPowerRequirement) {
		return nil, false
	}
	return o.BuyingPowerRequirement, true
}

// HasBuyingPowerRequirement returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasBuyingPowerRequirement() bool {
	if o != nil && !IsNil(o.BuyingPowerRequirement) {
		return true
	}

	return false
}

// SetBuyingPowerRequirement gets a reference to the given string and assigns it to the BuyingPowerRequirement field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetBuyingPowerRequirement(v string) {
	o.BuyingPowerRequirement = &v
}

// GetEstimatedProceeds returns the EstimatedProceeds field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetEstimatedProceeds() string {
	if o == nil || IsNil(o.EstimatedProceeds) {
		var ret string
		return ret
	}
	return *o.EstimatedProceeds
}

// GetEstimatedProceedsOk returns a tuple with the EstimatedProceeds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetEstimatedProceedsOk() (*string, bool) {
	if o == nil || IsNil(o.EstimatedProceeds) {
		return nil, false
	}
	return o.EstimatedProceeds, true
}

// HasEstimatedProceeds returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasEstimatedProceeds() bool {
	if o != nil && !IsNil(o.EstimatedProceeds) {
		return true
	}

	return false
}

// SetEstimatedProceeds gets a reference to the given string and assigns it to the EstimatedProceeds field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetEstimatedProceeds(v string) {
	o.EstimatedProceeds = &v
}

// GetOptionDetails returns the OptionDetails field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetOptionDetails() ComHellopublicUserapigatewayApiRestPreflightGatewayOptionDetails {
	if o == nil || IsNil(o.OptionDetails) {
		var ret ComHellopublicUserapigatewayApiRestPreflightGatewayOptionDetails
		return ret
	}
	return *o.OptionDetails
}

// GetOptionDetailsOk returns a tuple with the OptionDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetOptionDetailsOk() (*ComHellopublicUserapigatewayApiRestPreflightGatewayOptionDetails, bool) {
	if o == nil || IsNil(o.OptionDetails) {
		return nil, false
	}
	return o.OptionDetails, true
}

// HasOptionDetails returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasOptionDetails() bool {
	if o != nil && !IsNil(o.OptionDetails) {
		return true
	}

	return false
}

// SetOptionDetails gets a reference to the given ComHellopublicUserapigatewayApiRestPreflightGatewayOptionDetails and assigns it to the OptionDetails field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetOptionDetails(v ComHellopublicUserapigatewayApiRestPreflightGatewayOptionDetails) {
	o.OptionDetails = &v
}

// GetEstimatedOrderRebate returns the EstimatedOrderRebate field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetEstimatedOrderRebate() ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate {
	if o == nil || IsNil(o.EstimatedOrderRebate) {
		var ret ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate
		return ret
	}
	return *o.EstimatedOrderRebate
}

// GetEstimatedOrderRebateOk returns a tuple with the EstimatedOrderRebate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetEstimatedOrderRebateOk() (*ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate, bool) {
	if o == nil || IsNil(o.EstimatedOrderRebate) {
		return nil, false
	}
	return o.EstimatedOrderRebate, true
}

// HasEstimatedOrderRebate returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasEstimatedOrderRebate() bool {
	if o != nil && !IsNil(o.EstimatedOrderRebate) {
		return true
	}

	return false
}

// SetEstimatedOrderRebate gets a reference to the given ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate and assigns it to the EstimatedOrderRebate field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetEstimatedOrderRebate(v ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) {
	o.EstimatedOrderRebate = &v
}

// GetMarginRequirement returns the MarginRequirement field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetMarginRequirement() ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement {
	if o == nil || IsNil(o.MarginRequirement) {
		var ret ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement
		return ret
	}
	return *o.MarginRequirement
}

// GetMarginRequirementOk returns a tuple with the MarginRequirement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetMarginRequirementOk() (*ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement, bool) {
	if o == nil || IsNil(o.MarginRequirement) {
		return nil, false
	}
	return o.MarginRequirement, true
}

// HasMarginRequirement returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasMarginRequirement() bool {
	if o != nil && !IsNil(o.MarginRequirement) {
		return true
	}

	return false
}

// SetMarginRequirement gets a reference to the given ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement and assigns it to the MarginRequirement field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetMarginRequirement(v ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) {
	o.MarginRequirement = &v
}

// GetMarginImpact returns the MarginImpact field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetMarginImpact() ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact {
	if o == nil || IsNil(o.MarginImpact) {
		var ret ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact
		return ret
	}
	return *o.MarginImpact
}

// GetMarginImpactOk returns a tuple with the MarginImpact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetMarginImpactOk() (*ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact, bool) {
	if o == nil || IsNil(o.MarginImpact) {
		return nil, false
	}
	return o.MarginImpact, true
}

// HasMarginImpact returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasMarginImpact() bool {
	if o != nil && !IsNil(o.MarginImpact) {
		return true
	}

	return false
}

// SetMarginImpact gets a reference to the given ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact and assigns it to the MarginImpact field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetMarginImpact(v ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) {
	o.MarginImpact = &v
}

// GetPriceIncrement returns the PriceIncrement field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetPriceIncrement() ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement {
	if o == nil || IsNil(o.PriceIncrement) {
		var ret ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement
		return ret
	}
	return *o.PriceIncrement
}

// GetPriceIncrementOk returns a tuple with the PriceIncrement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) GetPriceIncrementOk() (*ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement, bool) {
	if o == nil || IsNil(o.PriceIncrement) {
		return nil, false
	}
	return o.PriceIncrement, true
}

// HasPriceIncrement returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) HasPriceIncrement() bool {
	if o != nil && !IsNil(o.PriceIncrement) {
		return true
	}

	return false
}

// SetPriceIncrement gets a reference to the given ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement and assigns it to the PriceIncrement field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) SetPriceIncrement(v ComHellopublicUserapigatewayApiRestPreflightGatewayPriceIncrement) {
	o.PriceIncrement = &v
}

func (o ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instrument"] = o.Instrument
	if !IsNil(o.Cusip) {
		toSerialize["cusip"] = o.Cusip
	}
	if !IsNil(o.RootSymbol) {
		toSerialize["rootSymbol"] = o.RootSymbol
	}
	if !IsNil(o.RootOptionSymbol) {
		toSerialize["rootOptionSymbol"] = o.RootOptionSymbol
	}
	if !IsNil(o.EstimatedCommission) {
		toSerialize["estimatedCommission"] = o.EstimatedCommission
	}
	if !IsNil(o.RegulatoryFees) {
		toSerialize["regulatoryFees"] = o.RegulatoryFees
	}
	if !IsNil(o.EstimatedIndexOptionFee) {
		toSerialize["estimatedIndexOptionFee"] = o.EstimatedIndexOptionFee
	}
	toSerialize["orderValue"] = o.OrderValue
	if !IsNil(o.EstimatedQuantity) {
		toSerialize["estimatedQuantity"] = o.EstimatedQuantity
	}
	if !IsNil(o.EstimatedCost) {
		toSerialize["estimatedCost"] = o.EstimatedCost
	}
	if !IsNil(o.BuyingPowerRequirement) {
		toSerialize["buyingPowerRequirement"] = o.BuyingPowerRequirement
	}
	if !IsNil(o.EstimatedProceeds) {
		toSerialize["estimatedProceeds"] = o.EstimatedProceeds
	}
	if !IsNil(o.OptionDetails) {
		toSerialize["optionDetails"] = o.OptionDetails
	}
	if !IsNil(o.EstimatedOrderRebate) {
		toSerialize["estimatedOrderRebate"] = o.EstimatedOrderRebate
	}
	if !IsNil(o.MarginRequirement) {
		toSerialize["marginRequirement"] = o.MarginRequirement
	}
	if !IsNil(o.MarginImpact) {
		toSerialize["marginImpact"] = o.MarginImpact
	}
	if !IsNil(o.PriceIncrement) {
		toSerialize["priceIncrement"] = o.PriceIncrement
	}
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instrument",
		"orderValue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse := _ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse(varComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse)

	return err
}

type NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse struct {
	value *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) Get() *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) Set(val *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse(val *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) *NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse {
	return &NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


