/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType Type of the account
type ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType string

// List of com_hellopublic_userapigateway_api_rest_portfolio_GatewayPortfolioAccount_accountType
const (
	BROKERAGE ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType = "BROKERAGE"
	HIGH_YIELD ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType = "HIGH_YIELD"
	BOND_ACCOUNT ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType = "BOND_ACCOUNT"
	RIA_ASSET ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType = "RIA_ASSET"
	TREASURY ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType = "TREASURY"
)

// All allowed values of ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType enum
var AllowedComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountTypeEnumValues = []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType{
	"BROKERAGE",
	"HIGH_YIELD",
	"BOND_ACCOUNT",
	"RIA_ASSET",
	"TREASURY",
}

func (v *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType", value)
}

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountTypeFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountTypeFromValue(v string) (*ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType, error) {
	ev := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_portfolio_GatewayPortfolioAccount_accountType value
func (v ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType) Ptr() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType struct {
	value *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType) Get() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType) Set(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType) *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType {
	return &NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountAccountType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

