/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity{}

// ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity Portfolio equity summary
type ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity struct {
	// Type of asset.
	Type string `json:"type"`
	// Total value for the given asset type.
	Value string `json:"value"`
	// The percentage of the portfolio this asset type constitutes.                                Percentage number is given with 2 decimals.
	PercentageOfPortfolio *string `json:"percentageOfPortfolio,omitempty"`
}

type _ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity instantiates a new ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity(type_ string, value string) *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity {
	this := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity{}
	this.Type = type_
	this.Value = value
	return &this
}

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityWithDefaults() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity {
	this := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity{}
	return &this
}

// GetType returns the Type field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) SetValue(v string) {
	o.Value = v
}

// GetPercentageOfPortfolio returns the PercentageOfPortfolio field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) GetPercentageOfPortfolio() string {
	if o == nil || IsNil(o.PercentageOfPortfolio) {
		var ret string
		return ret
	}
	return *o.PercentageOfPortfolio
}

// GetPercentageOfPortfolioOk returns a tuple with the PercentageOfPortfolio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) GetPercentageOfPortfolioOk() (*string, bool) {
	if o == nil || IsNil(o.PercentageOfPortfolio) {
		return nil, false
	}
	return o.PercentageOfPortfolio, true
}

// HasPercentageOfPortfolio returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) HasPercentageOfPortfolio() bool {
	if o != nil && !IsNil(o.PercentageOfPortfolio) {
		return true
	}

	return false
}

// SetPercentageOfPortfolio gets a reference to the given string and assigns it to the PercentageOfPortfolio field.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) SetPercentageOfPortfolio(v string) {
	o.PercentageOfPortfolio = &v
}

func (o ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["value"] = o.Value
	if !IsNil(o.PercentageOfPortfolio) {
		toSerialize["percentageOfPortfolio"] = o.PercentageOfPortfolio
	}
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity := _ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity(varComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity)

	return err
}

type NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity struct {
	value *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) Get() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) Set(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity {
	return &NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


