/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
)

// checks if the ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse{}

// ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse struct for ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse
type ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse struct {
	// The base symbol for which the option chain belongs.
	BaseSymbol *string `json:"baseSymbol,omitempty"`
	// List of call quotes for the given option chain.
	Calls []ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayQuote `json:"calls,omitempty"`
	// List of put quotes for the given option chain.
	Puts []ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayQuote `json:"puts,omitempty"`
}

// NewComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse instantiates a new ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse() *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse {
	this := ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse{}
	return &this
}

// NewComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponseWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponseWithDefaults() *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse {
	this := ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse{}
	return &this
}

// GetBaseSymbol returns the BaseSymbol field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) GetBaseSymbol() string {
	if o == nil || IsNil(o.BaseSymbol) {
		var ret string
		return ret
	}
	return *o.BaseSymbol
}

// GetBaseSymbolOk returns a tuple with the BaseSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) GetBaseSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.BaseSymbol) {
		return nil, false
	}
	return o.BaseSymbol, true
}

// HasBaseSymbol returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) HasBaseSymbol() bool {
	if o != nil && !IsNil(o.BaseSymbol) {
		return true
	}

	return false
}

// SetBaseSymbol gets a reference to the given string and assigns it to the BaseSymbol field.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) SetBaseSymbol(v string) {
	o.BaseSymbol = &v
}

// GetCalls returns the Calls field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) GetCalls() []ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayQuote {
	if o == nil || IsNil(o.Calls) {
		var ret []ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayQuote
		return ret
	}
	return o.Calls
}

// GetCallsOk returns a tuple with the Calls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) GetCallsOk() ([]ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayQuote, bool) {
	if o == nil || IsNil(o.Calls) {
		return nil, false
	}
	return o.Calls, true
}

// HasCalls returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) HasCalls() bool {
	if o != nil && !IsNil(o.Calls) {
		return true
	}

	return false
}

// SetCalls gets a reference to the given []ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayQuote and assigns it to the Calls field.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) SetCalls(v []ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayQuote) {
	o.Calls = v
}

// GetPuts returns the Puts field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) GetPuts() []ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayQuote {
	if o == nil || IsNil(o.Puts) {
		var ret []ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayQuote
		return ret
	}
	return o.Puts
}

// GetPutsOk returns a tuple with the Puts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) GetPutsOk() ([]ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayQuote, bool) {
	if o == nil || IsNil(o.Puts) {
		return nil, false
	}
	return o.Puts, true
}

// HasPuts returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) HasPuts() bool {
	if o != nil && !IsNil(o.Puts) {
		return true
	}

	return false
}

// SetPuts gets a reference to the given []ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayQuote and assigns it to the Puts field.
func (o *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) SetPuts(v []ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayQuote) {
	o.Puts = v
}

func (o ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BaseSymbol) {
		toSerialize["baseSymbol"] = o.BaseSymbol
	}
	if !IsNil(o.Calls) {
		toSerialize["calls"] = o.Calls
	}
	if !IsNil(o.Puts) {
		toSerialize["puts"] = o.Puts
	}
	return toSerialize, nil
}

type NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse struct {
	value *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) Get() *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) Set(val *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse(val *ComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) *NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse {
	return &NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestMarketdataQuoteGatewayOptionChainResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


