/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType the model 'ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType'
type ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType string

// List of com_hellopublic_userapigateway_api_rest_account_AccountSettings_brokerageAccountType
const (
	CASH ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType = "CASH"
	MARGIN ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType = "MARGIN"
)

// All allowed values of ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType enum
var AllowedComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountTypeEnumValues = []ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType{
	"CASH",
	"MARGIN",
}

func (v *ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType", value)
}

// NewComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountTypeFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountTypeFromValue(v string) (*ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType, error) {
	ev := ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_account_AccountSettings_brokerageAccountType value
func (v ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType) Ptr() *ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType struct {
	value *ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType) Get() *ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType) Set(val *ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType(val *ComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType) *NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType {
	return &NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsBrokerageAccountType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

