/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce The time in for the order
type ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce string

// List of com_hellopublic_userapigateway_api_rest_order_OrderExpiration_timeInForce
const (
	DAY ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce = "DAY"
	GTD ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce = "GTD"
)

// All allowed values of ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce enum
var AllowedComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForceEnumValues = []ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce{
	"DAY",
	"GTD",
}

func (v *ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce", value)
}

// NewComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForceFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForceFromValue(v string) (*ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce, error) {
	ev := ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_order_OrderExpiration_timeInForce value
func (v ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce) Ptr() *ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce struct {
	value *ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce) Get() *ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce) Set(val *ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce(val *ComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce) *NullableComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce {
	return &NullableComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderOrderExpirationTimeInForce) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

