/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto{}

// ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto struct for ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto
type ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto struct {
	Instrument ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument `json:"instrument"`
	Trading GetAllInstrumentsTradingFilterParameterInner `json:"trading"`
	FractionalTrading GetAllInstrumentsTradingFilterParameterInner `json:"fractionalTrading"`
	OptionTrading GetAllInstrumentsTradingFilterParameterInner `json:"optionTrading"`
	OptionSpreadTrading GetAllInstrumentsTradingFilterParameterInner `json:"optionSpreadTrading"`
}

type _ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto

// NewComHellopublicUserapigatewayApiRestOrderApiInstrumentDto instantiates a new ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestOrderApiInstrumentDto(instrument ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument, trading GetAllInstrumentsTradingFilterParameterInner, fractionalTrading GetAllInstrumentsTradingFilterParameterInner, optionTrading GetAllInstrumentsTradingFilterParameterInner, optionSpreadTrading GetAllInstrumentsTradingFilterParameterInner) *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto {
	this := ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto{}
	this.Instrument = instrument
	this.Trading = trading
	this.FractionalTrading = fractionalTrading
	this.OptionTrading = optionTrading
	this.OptionSpreadTrading = optionSpreadTrading
	return &this
}

// NewComHellopublicUserapigatewayApiRestOrderApiInstrumentDtoWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestOrderApiInstrumentDtoWithDefaults() *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto {
	this := ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto{}
	return &this
}

// GetInstrument returns the Instrument field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) GetInstrument() ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument
		return ret
	}

	return o.Instrument
}

// GetInstrumentOk returns a tuple with the Instrument field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) GetInstrumentOk() (*ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instrument, true
}

// SetInstrument sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) SetInstrument(v ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) {
	o.Instrument = v
}

// GetTrading returns the Trading field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) GetTrading() GetAllInstrumentsTradingFilterParameterInner {
	if o == nil {
		var ret GetAllInstrumentsTradingFilterParameterInner
		return ret
	}

	return o.Trading
}

// GetTradingOk returns a tuple with the Trading field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) GetTradingOk() (*GetAllInstrumentsTradingFilterParameterInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trading, true
}

// SetTrading sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) SetTrading(v GetAllInstrumentsTradingFilterParameterInner) {
	o.Trading = v
}

// GetFractionalTrading returns the FractionalTrading field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) GetFractionalTrading() GetAllInstrumentsTradingFilterParameterInner {
	if o == nil {
		var ret GetAllInstrumentsTradingFilterParameterInner
		return ret
	}

	return o.FractionalTrading
}

// GetFractionalTradingOk returns a tuple with the FractionalTrading field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) GetFractionalTradingOk() (*GetAllInstrumentsTradingFilterParameterInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FractionalTrading, true
}

// SetFractionalTrading sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) SetFractionalTrading(v GetAllInstrumentsTradingFilterParameterInner) {
	o.FractionalTrading = v
}

// GetOptionTrading returns the OptionTrading field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) GetOptionTrading() GetAllInstrumentsTradingFilterParameterInner {
	if o == nil {
		var ret GetAllInstrumentsTradingFilterParameterInner
		return ret
	}

	return o.OptionTrading
}

// GetOptionTradingOk returns a tuple with the OptionTrading field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) GetOptionTradingOk() (*GetAllInstrumentsTradingFilterParameterInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OptionTrading, true
}

// SetOptionTrading sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) SetOptionTrading(v GetAllInstrumentsTradingFilterParameterInner) {
	o.OptionTrading = v
}

// GetOptionSpreadTrading returns the OptionSpreadTrading field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) GetOptionSpreadTrading() GetAllInstrumentsTradingFilterParameterInner {
	if o == nil {
		var ret GetAllInstrumentsTradingFilterParameterInner
		return ret
	}

	return o.OptionSpreadTrading
}

// GetOptionSpreadTradingOk returns a tuple with the OptionSpreadTrading field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) GetOptionSpreadTradingOk() (*GetAllInstrumentsTradingFilterParameterInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OptionSpreadTrading, true
}

// SetOptionSpreadTrading sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) SetOptionSpreadTrading(v GetAllInstrumentsTradingFilterParameterInner) {
	o.OptionSpreadTrading = v
}

func (o ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instrument"] = o.Instrument
	toSerialize["trading"] = o.Trading
	toSerialize["fractionalTrading"] = o.FractionalTrading
	toSerialize["optionTrading"] = o.OptionTrading
	toSerialize["optionSpreadTrading"] = o.OptionSpreadTrading
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instrument",
		"trading",
		"fractionalTrading",
		"optionTrading",
		"optionSpreadTrading",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestOrderApiInstrumentDto := _ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestOrderApiInstrumentDto)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto(varComHellopublicUserapigatewayApiRestOrderApiInstrumentDto)

	return err
}

type NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentDto struct {
	value *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) Get() *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) Set(val *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestOrderApiInstrumentDto(val *ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) *NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentDto {
	return &NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentDto{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


