/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide The Order Side BUY/SELL. For Options also include the openCloseIndicator
type ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide string

// List of com_hellopublic_userapigateway_api_rest_preflight_PreflightSingleLegRequest_orderSide
const (
	BUY ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide = "BUY"
	SELL ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide = "SELL"
)

// All allowed values of ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide enum
var AllowedComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSideEnumValues = []ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide{
	"BUY",
	"SELL",
}

func (v *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSideEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide", value)
}

// NewComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSideFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSideFromValue(v string) (*ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide, error) {
	ev := ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSideEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSideEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_preflight_PreflightSingleLegRequest_orderSide value
func (v ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide) Ptr() *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide struct {
	value *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide) Get() *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide) Set(val *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide(val *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide) *NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide {
	return &NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

