/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
)

// checks if the ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact{}

// ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact struct for ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact
type ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact struct {
	MarginUsageImpact *string `json:"marginUsageImpact,omitempty"`
	InitialMarginRequirement *string `json:"initialMarginRequirement,omitempty"`
}

// NewComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact instantiates a new ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact() *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact {
	this := ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact{}
	return &this
}

// NewComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpactWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpactWithDefaults() *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact {
	this := ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact{}
	return &this
}

// GetMarginUsageImpact returns the MarginUsageImpact field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) GetMarginUsageImpact() string {
	if o == nil || IsNil(o.MarginUsageImpact) {
		var ret string
		return ret
	}
	return *o.MarginUsageImpact
}

// GetMarginUsageImpactOk returns a tuple with the MarginUsageImpact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) GetMarginUsageImpactOk() (*string, bool) {
	if o == nil || IsNil(o.MarginUsageImpact) {
		return nil, false
	}
	return o.MarginUsageImpact, true
}

// HasMarginUsageImpact returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) HasMarginUsageImpact() bool {
	if o != nil && !IsNil(o.MarginUsageImpact) {
		return true
	}

	return false
}

// SetMarginUsageImpact gets a reference to the given string and assigns it to the MarginUsageImpact field.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) SetMarginUsageImpact(v string) {
	o.MarginUsageImpact = &v
}

// GetInitialMarginRequirement returns the InitialMarginRequirement field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) GetInitialMarginRequirement() string {
	if o == nil || IsNil(o.InitialMarginRequirement) {
		var ret string
		return ret
	}
	return *o.InitialMarginRequirement
}

// GetInitialMarginRequirementOk returns a tuple with the InitialMarginRequirement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) GetInitialMarginRequirementOk() (*string, bool) {
	if o == nil || IsNil(o.InitialMarginRequirement) {
		return nil, false
	}
	return o.InitialMarginRequirement, true
}

// HasInitialMarginRequirement returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) HasInitialMarginRequirement() bool {
	if o != nil && !IsNil(o.InitialMarginRequirement) {
		return true
	}

	return false
}

// SetInitialMarginRequirement gets a reference to the given string and assigns it to the InitialMarginRequirement field.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) SetInitialMarginRequirement(v string) {
	o.InitialMarginRequirement = &v
}

func (o ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MarginUsageImpact) {
		toSerialize["marginUsageImpact"] = o.MarginUsageImpact
	}
	if !IsNil(o.InitialMarginRequirement) {
		toSerialize["initialMarginRequirement"] = o.InitialMarginRequirement
	}
	return toSerialize, nil
}

type NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact struct {
	value *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) Get() *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) Set(val *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact(val *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) *NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact {
	return &NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginImpact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


