/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus the model 'ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus'
type ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus string

// List of com_hellopublic_userapigateway_api_rest_order_GatewayOrder_status
const (
	NEW ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus = "NEW"
	PARTIALLY_FILLED ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus = "PARTIALLY_FILLED"
	CANCELLED ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus = "CANCELLED"
	QUEUED_CANCELLED ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus = "QUEUED_CANCELLED"
	FILLED ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus = "FILLED"
	REJECTED ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus = "REJECTED"
	PENDING_REPLACE ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus = "PENDING_REPLACE"
	PENDING_CANCEL ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus = "PENDING_CANCEL"
	EXPIRED ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus = "EXPIRED"
	REPLACED ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus = "REPLACED"
)

// All allowed values of ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus enum
var AllowedComHellopublicUserapigatewayApiRestOrderGatewayOrderStatusEnumValues = []ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus{
	"NEW",
	"PARTIALLY_FILLED",
	"CANCELLED",
	"QUEUED_CANCELLED",
	"FILLED",
	"REJECTED",
	"PENDING_REPLACE",
	"PENDING_CANCEL",
	"EXPIRED",
	"REPLACED",
}

func (v *ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestOrderGatewayOrderStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus", value)
}

// NewComHellopublicUserapigatewayApiRestOrderGatewayOrderStatusFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestOrderGatewayOrderStatusFromValue(v string) (*ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus, error) {
	ev := ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestOrderGatewayOrderStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestOrderGatewayOrderStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_order_GatewayOrder_status value
func (v ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus) Ptr() *ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus struct {
	value *ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus) Get() *ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus) Set(val *ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus(val *ComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus) *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus {
	return &NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

