/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
)

// checks if the ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement{}

// ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement struct for ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement
type ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement struct {
	LongMaintenanceRequirement *string `json:"longMaintenanceRequirement,omitempty"`
	LongInitialRequirement *string `json:"longInitialRequirement,omitempty"`
}

// NewComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement instantiates a new ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement() *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement {
	this := ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement{}
	return &this
}

// NewComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirementWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirementWithDefaults() *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement {
	this := ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement{}
	return &this
}

// GetLongMaintenanceRequirement returns the LongMaintenanceRequirement field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) GetLongMaintenanceRequirement() string {
	if o == nil || IsNil(o.LongMaintenanceRequirement) {
		var ret string
		return ret
	}
	return *o.LongMaintenanceRequirement
}

// GetLongMaintenanceRequirementOk returns a tuple with the LongMaintenanceRequirement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) GetLongMaintenanceRequirementOk() (*string, bool) {
	if o == nil || IsNil(o.LongMaintenanceRequirement) {
		return nil, false
	}
	return o.LongMaintenanceRequirement, true
}

// HasLongMaintenanceRequirement returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) HasLongMaintenanceRequirement() bool {
	if o != nil && !IsNil(o.LongMaintenanceRequirement) {
		return true
	}

	return false
}

// SetLongMaintenanceRequirement gets a reference to the given string and assigns it to the LongMaintenanceRequirement field.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) SetLongMaintenanceRequirement(v string) {
	o.LongMaintenanceRequirement = &v
}

// GetLongInitialRequirement returns the LongInitialRequirement field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) GetLongInitialRequirement() string {
	if o == nil || IsNil(o.LongInitialRequirement) {
		var ret string
		return ret
	}
	return *o.LongInitialRequirement
}

// GetLongInitialRequirementOk returns a tuple with the LongInitialRequirement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) GetLongInitialRequirementOk() (*string, bool) {
	if o == nil || IsNil(o.LongInitialRequirement) {
		return nil, false
	}
	return o.LongInitialRequirement, true
}

// HasLongInitialRequirement returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) HasLongInitialRequirement() bool {
	if o != nil && !IsNil(o.LongInitialRequirement) {
		return true
	}

	return false
}

// SetLongInitialRequirement gets a reference to the given string and assigns it to the LongInitialRequirement field.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) SetLongInitialRequirement(v string) {
	o.LongInitialRequirement = &v
}

func (o ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LongMaintenanceRequirement) {
		toSerialize["longMaintenanceRequirement"] = o.LongMaintenanceRequirement
	}
	if !IsNil(o.LongInitialRequirement) {
		toSerialize["longInitialRequirement"] = o.LongInitialRequirement
	}
	return toSerialize, nil
}

type NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement struct {
	value *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) Get() *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) Set(val *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement(val *ComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) *NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement {
	return &NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightGatewayMarginRequirement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


