/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
)

// checks if the ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse{}

// ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse struct for ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse
type ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse struct {
	Accounts []ComHellopublicUserapigatewayApiRestAccountAccountSettings `json:"accounts,omitempty"`
}

// NewComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse instantiates a new ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse() *ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse {
	this := ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse{}
	return &this
}

// NewComHellopublicUserapigatewayApiRestAccountAccountSettingsResponseWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestAccountAccountSettingsResponseWithDefaults() *ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse {
	this := ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse{}
	return &this
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) GetAccounts() []ComHellopublicUserapigatewayApiRestAccountAccountSettings {
	if o == nil || IsNil(o.Accounts) {
		var ret []ComHellopublicUserapigatewayApiRestAccountAccountSettings
		return ret
	}
	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) GetAccountsOk() ([]ComHellopublicUserapigatewayApiRestAccountAccountSettings, bool) {
	if o == nil || IsNil(o.Accounts) {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) HasAccounts() bool {
	if o != nil && !IsNil(o.Accounts) {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []ComHellopublicUserapigatewayApiRestAccountAccountSettings and assigns it to the Accounts field.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) SetAccounts(v []ComHellopublicUserapigatewayApiRestAccountAccountSettings) {
	o.Accounts = v
}

func (o ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Accounts) {
		toSerialize["accounts"] = o.Accounts
	}
	return toSerialize, nil
}

type NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse struct {
	value *ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) Get() *ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) Set(val *ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse(val *ComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) *NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse {
	return &NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestAccountAccountSettingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


