/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
)

// checks if the ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse{}

// ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse struct for ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse
type ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse struct {
	// List of portfolios
	Accounts []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount `json:"accounts,omitempty"`
}

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse instantiates a new ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse {
	this := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse{}
	return &this
}

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponseWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponseWithDefaults() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse {
	this := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse{}
	return &this
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) GetAccounts() []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount {
	if o == nil || IsNil(o.Accounts) {
		var ret []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount
		return ret
	}
	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) GetAccountsOk() ([]ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount, bool) {
	if o == nil || IsNil(o.Accounts) {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) HasAccounts() bool {
	if o != nil && !IsNil(o.Accounts) {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount and assigns it to the Accounts field.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) SetAccounts(v []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccount) {
	o.Accounts = v
}

func (o ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Accounts) {
		toSerialize["accounts"] = o.Accounts
	}
	return toSerialize, nil
}

type NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse struct {
	value *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) Get() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) Set(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse {
	return &NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


