/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator required when instrument.type = OPTION, used to determine if the leg is buy-to-open or buy-to-close
type ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator string

// List of com_hellopublic_userapigateway_api_rest_order_GatewayOrderLeg_openCloseIndicator
const (
	OPEN ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator = "OPEN"
	CLOSE ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator = "CLOSE"
)

// All allowed values of ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator enum
var AllowedComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicatorEnumValues = []ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator{
	"OPEN",
	"CLOSE",
}

func (v *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicatorEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator", value)
}

// NewComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicatorFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicatorFromValue(v string) (*ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator, error) {
	ev := ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicatorEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicatorEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_order_GatewayOrderLeg_openCloseIndicator value
func (v ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator) Ptr() *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator struct {
	value *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator) Get() *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator) Set(val *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator(val *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator) *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator {
	return &NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

