/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestUserAccountKyc type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestUserAccountKyc{}

// ComHellopublicUserapigatewayApiRestUserAccountKyc struct for ComHellopublicUserapigatewayApiRestUserAccountKyc
type ComHellopublicUserapigatewayApiRestUserAccountKyc struct {
	AccountNumber string `json:"accountNumber"`
	AccountType ComHellopublicUserapigatewayApiRestUserAccountKycAccountType `json:"accountType"`
	Objective *ComHellopublicUserapigatewayApiRestUserAccountKycObjective `json:"objective,omitempty"`
	RiskTolerance *ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance `json:"riskTolerance,omitempty"`
}

type _ComHellopublicUserapigatewayApiRestUserAccountKyc ComHellopublicUserapigatewayApiRestUserAccountKyc

// NewComHellopublicUserapigatewayApiRestUserAccountKyc instantiates a new ComHellopublicUserapigatewayApiRestUserAccountKyc object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestUserAccountKyc(accountNumber string, accountType ComHellopublicUserapigatewayApiRestUserAccountKycAccountType) *ComHellopublicUserapigatewayApiRestUserAccountKyc {
	this := ComHellopublicUserapigatewayApiRestUserAccountKyc{}
	this.AccountNumber = accountNumber
	this.AccountType = accountType
	return &this
}

// NewComHellopublicUserapigatewayApiRestUserAccountKycWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestUserAccountKyc object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestUserAccountKycWithDefaults() *ComHellopublicUserapigatewayApiRestUserAccountKyc {
	this := ComHellopublicUserapigatewayApiRestUserAccountKyc{}
	return &this
}

// GetAccountNumber returns the AccountNumber field value
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) GetAccountNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountNumber
}

// GetAccountNumberOk returns a tuple with the AccountNumber field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) GetAccountNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountNumber, true
}

// SetAccountNumber sets field value
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) SetAccountNumber(v string) {
	o.AccountNumber = v
}

// GetAccountType returns the AccountType field value
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) GetAccountType() ComHellopublicUserapigatewayApiRestUserAccountKycAccountType {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestUserAccountKycAccountType
		return ret
	}

	return o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) GetAccountTypeOk() (*ComHellopublicUserapigatewayApiRestUserAccountKycAccountType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountType, true
}

// SetAccountType sets field value
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) SetAccountType(v ComHellopublicUserapigatewayApiRestUserAccountKycAccountType) {
	o.AccountType = v
}

// GetObjective returns the Objective field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) GetObjective() ComHellopublicUserapigatewayApiRestUserAccountKycObjective {
	if o == nil || IsNil(o.Objective) {
		var ret ComHellopublicUserapigatewayApiRestUserAccountKycObjective
		return ret
	}
	return *o.Objective
}

// GetObjectiveOk returns a tuple with the Objective field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) GetObjectiveOk() (*ComHellopublicUserapigatewayApiRestUserAccountKycObjective, bool) {
	if o == nil || IsNil(o.Objective) {
		return nil, false
	}
	return o.Objective, true
}

// HasObjective returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) HasObjective() bool {
	if o != nil && !IsNil(o.Objective) {
		return true
	}

	return false
}

// SetObjective gets a reference to the given ComHellopublicUserapigatewayApiRestUserAccountKycObjective and assigns it to the Objective field.
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) SetObjective(v ComHellopublicUserapigatewayApiRestUserAccountKycObjective) {
	o.Objective = &v
}

// GetRiskTolerance returns the RiskTolerance field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) GetRiskTolerance() ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance {
	if o == nil || IsNil(o.RiskTolerance) {
		var ret ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance
		return ret
	}
	return *o.RiskTolerance
}

// GetRiskToleranceOk returns a tuple with the RiskTolerance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) GetRiskToleranceOk() (*ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance, bool) {
	if o == nil || IsNil(o.RiskTolerance) {
		return nil, false
	}
	return o.RiskTolerance, true
}

// HasRiskTolerance returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) HasRiskTolerance() bool {
	if o != nil && !IsNil(o.RiskTolerance) {
		return true
	}

	return false
}

// SetRiskTolerance gets a reference to the given ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance and assigns it to the RiskTolerance field.
func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) SetRiskTolerance(v ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance) {
	o.RiskTolerance = &v
}

func (o ComHellopublicUserapigatewayApiRestUserAccountKyc) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestUserAccountKyc) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountNumber"] = o.AccountNumber
	toSerialize["accountType"] = o.AccountType
	if !IsNil(o.Objective) {
		toSerialize["objective"] = o.Objective
	}
	if !IsNil(o.RiskTolerance) {
		toSerialize["riskTolerance"] = o.RiskTolerance
	}
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestUserAccountKyc) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountNumber",
		"accountType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestUserAccountKyc := _ComHellopublicUserapigatewayApiRestUserAccountKyc{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestUserAccountKyc)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestUserAccountKyc(varComHellopublicUserapigatewayApiRestUserAccountKyc)

	return err
}

type NullableComHellopublicUserapigatewayApiRestUserAccountKyc struct {
	value *ComHellopublicUserapigatewayApiRestUserAccountKyc
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestUserAccountKyc) Get() *ComHellopublicUserapigatewayApiRestUserAccountKyc {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestUserAccountKyc) Set(val *ComHellopublicUserapigatewayApiRestUserAccountKyc) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestUserAccountKyc) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestUserAccountKyc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestUserAccountKyc(val *ComHellopublicUserapigatewayApiRestUserAccountKyc) *NullableComHellopublicUserapigatewayApiRestUserAccountKyc {
	return &NullableComHellopublicUserapigatewayApiRestUserAccountKyc{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestUserAccountKyc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestUserAccountKyc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


