/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
)

// checks if the ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse{}

// ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse struct for ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse
type ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse struct {
	Instruments []ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto `json:"instruments,omitempty"`
}

// NewComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse instantiates a new ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse() *ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse {
	this := ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse{}
	return &this
}

// NewComHellopublicUserapigatewayApiRestOrderApiInstrumentResponseWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestOrderApiInstrumentResponseWithDefaults() *ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse {
	this := ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse{}
	return &this
}

// GetInstruments returns the Instruments field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) GetInstruments() []ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto {
	if o == nil || IsNil(o.Instruments) {
		var ret []ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto
		return ret
	}
	return o.Instruments
}

// GetInstrumentsOk returns a tuple with the Instruments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) GetInstrumentsOk() ([]ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto, bool) {
	if o == nil || IsNil(o.Instruments) {
		return nil, false
	}
	return o.Instruments, true
}

// HasInstruments returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) HasInstruments() bool {
	if o != nil && !IsNil(o.Instruments) {
		return true
	}

	return false
}

// SetInstruments gets a reference to the given []ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto and assigns it to the Instruments field.
func (o *ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) SetInstruments(v []ComHellopublicUserapigatewayApiRestOrderApiInstrumentDto) {
	o.Instruments = v
}

func (o ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Instruments) {
		toSerialize["instruments"] = o.Instruments
	}
	return toSerialize, nil
}

type NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse struct {
	value *ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) Get() *ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) Set(val *ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse(val *ComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) *NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse {
	return &NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderApiInstrumentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


