/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType the model 'ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType'
type ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType string

// List of com_hellopublic_userapigateway_api_rest_portfolio_GatewayPortfolioInstrument_type
const (
	EQUITY ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType = "EQUITY"
	OPTION ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType = "OPTION"
	CRYPTO ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType = "CRYPTO"
	ALT ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType = "ALT"
	TREASURY ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType = "TREASURY"
	BOND ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType = "BOND"
	INDEX ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType = "INDEX"
)

// All allowed values of ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType enum
var AllowedComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentTypeEnumValues = []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType{
	"EQUITY",
	"OPTION",
	"CRYPTO",
	"ALT",
	"TREASURY",
	"BOND",
	"INDEX",
}

func (v *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType", value)
}

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentTypeFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentTypeFromValue(v string) (*ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType, error) {
	ev := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_portfolio_GatewayPortfolioInstrument_type value
func (v ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType) Ptr() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType struct {
	value *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType) Get() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType) Set(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType) *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType {
	return &NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

