/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator Used for options only. Indicates if this is BUY to OPEN/CLOSE
type ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator string

// List of com_hellopublic_userapigateway_api_rest_preflight_PreflightSingleLegRequest_openCloseIndicator
const (
	OPEN ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator = "OPEN"
	CLOSE ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator = "CLOSE"
)

// All allowed values of ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator enum
var AllowedComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicatorEnumValues = []ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator{
	"OPEN",
	"CLOSE",
}

func (v *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicatorEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator", value)
}

// NewComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicatorFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicatorFromValue(v string) (*ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator, error) {
	ev := ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicatorEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicatorEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_preflight_PreflightSingleLegRequest_openCloseIndicator value
func (v ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator) Ptr() *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator struct {
	value *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator) Get() *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator) Set(val *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator(val *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator) *NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator {
	return &NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

