/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
)

// checks if the ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument{}

// ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument struct for ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument
type ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument struct {
	Symbol *string `json:"symbol,omitempty"`
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument instantiates a new ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument {
	this := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument{}
	return &this
}

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrumentWithDefaults() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument {
	this := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument{}
	return &this
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) SetSymbol(v string) {
	o.Symbol = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) SetType(v string) {
	o.Type = &v
}

func (o ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument struct {
	value *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) Get() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) Set(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument {
	return &NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioInstrument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


