/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestOrderApiOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestOrderApiOrderRequest{}

// ComHellopublicUserapigatewayApiRestOrderApiOrderRequest Used for orders placed via the UserApiGatewayService or other service where the order is just a single request and the orderId is generated by the client
type ComHellopublicUserapigatewayApiRestOrderApiOrderRequest struct {
	// The OrderId, globally unique over time. This is also the deduplication key, if it is reused (on the same account) the operation is idempotent.  If you re-submit the order because of a read timeout, do not edit any properties. If the order was placed on the first request, altering properties  will not have an effect.
	OrderId string `json:"orderId"`
	Instrument ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument `json:"instrument"`
	OrderSide ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide `json:"orderSide"`
	OrderType ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderType `json:"orderType"`
	Expiration ComHellopublicUserapigatewayApiRestOrderOrderExpiration `json:"expiration"`
	// The order quantity. Used when buying/selling whole shares and when selling fractional.  Mutually exclusive with `amount`
	Quantity *string `json:"quantity,omitempty"`
	// The order amount. Used when buying/selling shares for a specific notional value
	Amount *string `json:"amount,omitempty"`
	// The limit price. Used when orderType = LIMIT or orderType = STOP_LIMIT
	LimitPrice *string `json:"limitPrice,omitempty"`
	// The stop price. Used when orderType = STOP or orderType = STOP_LIMIT
	StopPrice *string `json:"stopPrice,omitempty"`
	OpenCloseIndicator *ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator `json:"openCloseIndicator,omitempty"`
}

type _ComHellopublicUserapigatewayApiRestOrderApiOrderRequest ComHellopublicUserapigatewayApiRestOrderApiOrderRequest

// NewComHellopublicUserapigatewayApiRestOrderApiOrderRequest instantiates a new ComHellopublicUserapigatewayApiRestOrderApiOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestOrderApiOrderRequest(orderId string, instrument ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument, orderSide ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide, orderType ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderType, expiration ComHellopublicUserapigatewayApiRestOrderOrderExpiration) *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest {
	this := ComHellopublicUserapigatewayApiRestOrderApiOrderRequest{}
	this.OrderId = orderId
	this.Instrument = instrument
	this.OrderSide = orderSide
	this.OrderType = orderType
	this.Expiration = expiration
	return &this
}

// NewComHellopublicUserapigatewayApiRestOrderApiOrderRequestWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestOrderApiOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestOrderApiOrderRequestWithDefaults() *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest {
	this := ComHellopublicUserapigatewayApiRestOrderApiOrderRequest{}
	return &this
}

// GetOrderId returns the OrderId field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) SetOrderId(v string) {
	o.OrderId = v
}

// GetInstrument returns the Instrument field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetInstrument() ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument
		return ret
	}

	return o.Instrument
}

// GetInstrumentOk returns a tuple with the Instrument field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetInstrumentOk() (*ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instrument, true
}

// SetInstrument sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) SetInstrument(v ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) {
	o.Instrument = v
}

// GetOrderSide returns the OrderSide field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetOrderSide() ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide
		return ret
	}

	return o.OrderSide
}

// GetOrderSideOk returns a tuple with the OrderSide field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetOrderSideOk() (*ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderSide, true
}

// SetOrderSide sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) SetOrderSide(v ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderSide) {
	o.OrderSide = v
}

// GetOrderType returns the OrderType field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetOrderType() ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderType {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderType
		return ret
	}

	return o.OrderType
}

// GetOrderTypeOk returns a tuple with the OrderType field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetOrderTypeOk() (*ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderType, true
}

// SetOrderType sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) SetOrderType(v ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOrderType) {
	o.OrderType = v
}

// GetExpiration returns the Expiration field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetExpiration() ComHellopublicUserapigatewayApiRestOrderOrderExpiration {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestOrderOrderExpiration
		return ret
	}

	return o.Expiration
}

// GetExpirationOk returns a tuple with the Expiration field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetExpirationOk() (*ComHellopublicUserapigatewayApiRestOrderOrderExpiration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expiration, true
}

// SetExpiration sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) SetExpiration(v ComHellopublicUserapigatewayApiRestOrderOrderExpiration) {
	o.Expiration = v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetQuantity() string {
	if o == nil || IsNil(o.Quantity) {
		var ret string
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given string and assigns it to the Quantity field.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) SetQuantity(v string) {
	o.Quantity = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) SetAmount(v string) {
	o.Amount = &v
}

// GetLimitPrice returns the LimitPrice field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetLimitPrice() string {
	if o == nil || IsNil(o.LimitPrice) {
		var ret string
		return ret
	}
	return *o.LimitPrice
}

// GetLimitPriceOk returns a tuple with the LimitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetLimitPriceOk() (*string, bool) {
	if o == nil || IsNil(o.LimitPrice) {
		return nil, false
	}
	return o.LimitPrice, true
}

// HasLimitPrice returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) HasLimitPrice() bool {
	if o != nil && !IsNil(o.LimitPrice) {
		return true
	}

	return false
}

// SetLimitPrice gets a reference to the given string and assigns it to the LimitPrice field.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) SetLimitPrice(v string) {
	o.LimitPrice = &v
}

// GetStopPrice returns the StopPrice field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetStopPrice() string {
	if o == nil || IsNil(o.StopPrice) {
		var ret string
		return ret
	}
	return *o.StopPrice
}

// GetStopPriceOk returns a tuple with the StopPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetStopPriceOk() (*string, bool) {
	if o == nil || IsNil(o.StopPrice) {
		return nil, false
	}
	return o.StopPrice, true
}

// HasStopPrice returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) HasStopPrice() bool {
	if o != nil && !IsNil(o.StopPrice) {
		return true
	}

	return false
}

// SetStopPrice gets a reference to the given string and assigns it to the StopPrice field.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) SetStopPrice(v string) {
	o.StopPrice = &v
}

// GetOpenCloseIndicator returns the OpenCloseIndicator field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetOpenCloseIndicator() ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator {
	if o == nil || IsNil(o.OpenCloseIndicator) {
		var ret ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator
		return ret
	}
	return *o.OpenCloseIndicator
}

// GetOpenCloseIndicatorOk returns a tuple with the OpenCloseIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) GetOpenCloseIndicatorOk() (*ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator, bool) {
	if o == nil || IsNil(o.OpenCloseIndicator) {
		return nil, false
	}
	return o.OpenCloseIndicator, true
}

// HasOpenCloseIndicator returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) HasOpenCloseIndicator() bool {
	if o != nil && !IsNil(o.OpenCloseIndicator) {
		return true
	}

	return false
}

// SetOpenCloseIndicator gets a reference to the given ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator and assigns it to the OpenCloseIndicator field.
func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) SetOpenCloseIndicator(v ComHellopublicUserapigatewayApiRestPreflightPreflightSingleLegRequestOpenCloseIndicator) {
	o.OpenCloseIndicator = &v
}

func (o ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["orderId"] = o.OrderId
	toSerialize["instrument"] = o.Instrument
	toSerialize["orderSide"] = o.OrderSide
	toSerialize["orderType"] = o.OrderType
	toSerialize["expiration"] = o.Expiration
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.LimitPrice) {
		toSerialize["limitPrice"] = o.LimitPrice
	}
	if !IsNil(o.StopPrice) {
		toSerialize["stopPrice"] = o.StopPrice
	}
	if !IsNil(o.OpenCloseIndicator) {
		toSerialize["openCloseIndicator"] = o.OpenCloseIndicator
	}
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"orderId",
		"instrument",
		"orderSide",
		"orderType",
		"expiration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestOrderApiOrderRequest := _ComHellopublicUserapigatewayApiRestOrderApiOrderRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestOrderApiOrderRequest)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestOrderApiOrderRequest(varComHellopublicUserapigatewayApiRestOrderApiOrderRequest)

	return err
}

type NullableComHellopublicUserapigatewayApiRestOrderApiOrderRequest struct {
	value *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestOrderApiOrderRequest) Get() *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderApiOrderRequest) Set(val *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestOrderApiOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderApiOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestOrderApiOrderRequest(val *ComHellopublicUserapigatewayApiRestOrderApiOrderRequest) *NullableComHellopublicUserapigatewayApiRestOrderApiOrderRequest {
	return &NullableComHellopublicUserapigatewayApiRestOrderApiOrderRequest{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestOrderApiOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderApiOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


