/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower{}

// ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower struct for ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower
type ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower struct {
	// Buying power available for trading on cash only without taking loans.
	CashOnlyBuyingPower string `json:"cashOnlyBuyingPower"`
	// Buying power available for trading marginable assets.
	BuyingPower string `json:"buyingPower"`
	// Buying power available for trading options.
	OptionsBuyingPower string `json:"optionsBuyingPower"`
}

type _ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower instantiates a new ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower(cashOnlyBuyingPower string, buyingPower string, optionsBuyingPower string) *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower {
	this := ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower{}
	this.CashOnlyBuyingPower = cashOnlyBuyingPower
	this.BuyingPower = buyingPower
	this.OptionsBuyingPower = optionsBuyingPower
	return &this
}

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPowerWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPowerWithDefaults() *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower {
	this := ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower{}
	return &this
}

// GetCashOnlyBuyingPower returns the CashOnlyBuyingPower field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) GetCashOnlyBuyingPower() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CashOnlyBuyingPower
}

// GetCashOnlyBuyingPowerOk returns a tuple with the CashOnlyBuyingPower field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) GetCashOnlyBuyingPowerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CashOnlyBuyingPower, true
}

// SetCashOnlyBuyingPower sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) SetCashOnlyBuyingPower(v string) {
	o.CashOnlyBuyingPower = v
}

// GetBuyingPower returns the BuyingPower field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) GetBuyingPower() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuyingPower
}

// GetBuyingPowerOk returns a tuple with the BuyingPower field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) GetBuyingPowerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuyingPower, true
}

// SetBuyingPower sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) SetBuyingPower(v string) {
	o.BuyingPower = v
}

// GetOptionsBuyingPower returns the OptionsBuyingPower field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) GetOptionsBuyingPower() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OptionsBuyingPower
}

// GetOptionsBuyingPowerOk returns a tuple with the OptionsBuyingPower field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) GetOptionsBuyingPowerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OptionsBuyingPower, true
}

// SetOptionsBuyingPower sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) SetOptionsBuyingPower(v string) {
	o.OptionsBuyingPower = v
}

func (o ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cashOnlyBuyingPower"] = o.CashOnlyBuyingPower
	toSerialize["buyingPower"] = o.BuyingPower
	toSerialize["optionsBuyingPower"] = o.OptionsBuyingPower
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cashOnlyBuyingPower",
		"buyingPower",
		"optionsBuyingPower",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower := _ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower(varComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower)

	return err
}

type NullableComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower struct {
	value *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) Get() *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) Set(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower {
	return &NullableComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


