/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType The security type of the transaction
type ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType string

// List of com_hellopublic_userapigateway_api_rest_history_GatewayHistoryTransaction_securityType
const (
	EQUITY ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType = "EQUITY"
	OPTION ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType = "OPTION"
	CRYPTO ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType = "CRYPTO"
	ALT ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType = "ALT"
	TREASURY ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType = "TREASURY"
	BOND ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType = "BOND"
)

// All allowed values of ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType enum
var AllowedComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityTypeEnumValues = []ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType{
	"EQUITY",
	"OPTION",
	"CRYPTO",
	"ALT",
	"TREASURY",
	"BOND",
}

func (v *ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType", value)
}

// NewComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityTypeFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityTypeFromValue(v string) (*ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType, error) {
	ev := ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_history_GatewayHistoryTransaction_securityType value
func (v ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType) Ptr() *ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType struct {
	value *ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType) Get() *ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType) Set(val *ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType(val *ComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType) *NullableComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType {
	return &NullableComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestHistoryGatewayHistoryTransactionSecurityType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

