/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2{}

// ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 Portfolio for the account
type ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 struct {
	// Id of the account
	AccountId string `json:"accountId"`
	// Type of the account
	AccountType string `json:"accountType"`
	BuyingPower ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower `json:"buyingPower"`
	// List of equity summaries
	Equity []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 `json:"equity"`
	// List of positions
	Positions []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioPosition `json:"positions"`
	Orders []ComHellopublicUserapigatewayApiRestOrderGatewayOrder `json:"orders"`
}

type _ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 instantiates a new ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2(accountId string, accountType string, buyingPower ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower, equity []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2, positions []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioPosition, orders []ComHellopublicUserapigatewayApiRestOrderGatewayOrder) *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 {
	this := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2{}
	this.AccountId = accountId
	this.AccountType = accountType
	this.BuyingPower = buyingPower
	this.Equity = equity
	this.Positions = positions
	this.Orders = orders
	return &this
}

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2WithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2WithDefaults() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 {
	this := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) SetAccountId(v string) {
	o.AccountId = v
}

// GetAccountType returns the AccountType field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) GetAccountType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) GetAccountTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountType, true
}

// SetAccountType sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) SetAccountType(v string) {
	o.AccountType = v
}

// GetBuyingPower returns the BuyingPower field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) GetBuyingPower() ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower
		return ret
	}

	return o.BuyingPower
}

// GetBuyingPowerOk returns a tuple with the BuyingPower field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) GetBuyingPowerOk() (*ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuyingPower, true
}

// SetBuyingPower sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) SetBuyingPower(v ComHellopublicUserapigatewayApiRestPortfolioGatewayBuyingPower) {
	o.BuyingPower = v
}

// GetEquity returns the Equity field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) GetEquity() []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2 {
	if o == nil {
		var ret []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2
		return ret
	}

	return o.Equity
}

// GetEquityOk returns a tuple with the Equity field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) GetEquityOk() ([]ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2, bool) {
	if o == nil {
		return nil, false
	}
	return o.Equity, true
}

// SetEquity sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) SetEquity(v []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2) {
	o.Equity = v
}

// GetPositions returns the Positions field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) GetPositions() []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioPosition {
	if o == nil {
		var ret []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioPosition
		return ret
	}

	return o.Positions
}

// GetPositionsOk returns a tuple with the Positions field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) GetPositionsOk() ([]ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioPosition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Positions, true
}

// SetPositions sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) SetPositions(v []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioPosition) {
	o.Positions = v
}

// GetOrders returns the Orders field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) GetOrders() []ComHellopublicUserapigatewayApiRestOrderGatewayOrder {
	if o == nil {
		var ret []ComHellopublicUserapigatewayApiRestOrderGatewayOrder
		return ret
	}

	return o.Orders
}

// GetOrdersOk returns a tuple with the Orders field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) GetOrdersOk() ([]ComHellopublicUserapigatewayApiRestOrderGatewayOrder, bool) {
	if o == nil {
		return nil, false
	}
	return o.Orders, true
}

// SetOrders sets field value
func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) SetOrders(v []ComHellopublicUserapigatewayApiRestOrderGatewayOrder) {
	o.Orders = v
}

func (o ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountId"] = o.AccountId
	toSerialize["accountType"] = o.AccountType
	toSerialize["buyingPower"] = o.BuyingPower
	toSerialize["equity"] = o.Equity
	toSerialize["positions"] = o.Positions
	toSerialize["orders"] = o.Orders
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountId",
		"accountType",
		"buyingPower",
		"equity",
		"positions",
		"orders",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 := _ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2(varComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2)

	return err
}

type NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 struct {
	value *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) Get() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) Set(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2 {
	return &NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioAccountV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


