/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance the model 'ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance'
type ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance string

// List of com_hellopublic_userapigateway_api_rest_user_AccountKyc_riskTolerance
const (
	LOW ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance = "LOW"
	MEDIUM ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance = "MEDIUM"
	HIGH ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance = "HIGH"
)

// All allowed values of ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance enum
var AllowedComHellopublicUserapigatewayApiRestUserAccountKycRiskToleranceEnumValues = []ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance{
	"LOW",
	"MEDIUM",
	"HIGH",
}

func (v *ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestUserAccountKycRiskToleranceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance", value)
}

// NewComHellopublicUserapigatewayApiRestUserAccountKycRiskToleranceFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestUserAccountKycRiskToleranceFromValue(v string) (*ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance, error) {
	ev := ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestUserAccountKycRiskToleranceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestUserAccountKycRiskToleranceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_user_AccountKyc_riskTolerance value
func (v ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance) Ptr() *ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance struct {
	value *ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance) Get() *ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance) Set(val *ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance(val *ComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance) *NullableComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance {
	return &NullableComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestUserAccountKycRiskTolerance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

