/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
)

// checks if the ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate{}

// ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate struct for ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate
type ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate struct {
	EstimatedOptionRebate *string `json:"estimatedOptionRebate,omitempty"`
	OptionRebatePercent *int32 `json:"optionRebatePercent,omitempty"`
	PerContractRebate *string `json:"perContractRebate,omitempty"`
}

// NewComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate instantiates a new ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate() *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate {
	this := ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate{}
	return &this
}

// NewComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebateWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebateWithDefaults() *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate {
	this := ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate{}
	return &this
}

// GetEstimatedOptionRebate returns the EstimatedOptionRebate field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) GetEstimatedOptionRebate() string {
	if o == nil || IsNil(o.EstimatedOptionRebate) {
		var ret string
		return ret
	}
	return *o.EstimatedOptionRebate
}

// GetEstimatedOptionRebateOk returns a tuple with the EstimatedOptionRebate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) GetEstimatedOptionRebateOk() (*string, bool) {
	if o == nil || IsNil(o.EstimatedOptionRebate) {
		return nil, false
	}
	return o.EstimatedOptionRebate, true
}

// HasEstimatedOptionRebate returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) HasEstimatedOptionRebate() bool {
	if o != nil && !IsNil(o.EstimatedOptionRebate) {
		return true
	}

	return false
}

// SetEstimatedOptionRebate gets a reference to the given string and assigns it to the EstimatedOptionRebate field.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) SetEstimatedOptionRebate(v string) {
	o.EstimatedOptionRebate = &v
}

// GetOptionRebatePercent returns the OptionRebatePercent field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) GetOptionRebatePercent() int32 {
	if o == nil || IsNil(o.OptionRebatePercent) {
		var ret int32
		return ret
	}
	return *o.OptionRebatePercent
}

// GetOptionRebatePercentOk returns a tuple with the OptionRebatePercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) GetOptionRebatePercentOk() (*int32, bool) {
	if o == nil || IsNil(o.OptionRebatePercent) {
		return nil, false
	}
	return o.OptionRebatePercent, true
}

// HasOptionRebatePercent returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) HasOptionRebatePercent() bool {
	if o != nil && !IsNil(o.OptionRebatePercent) {
		return true
	}

	return false
}

// SetOptionRebatePercent gets a reference to the given int32 and assigns it to the OptionRebatePercent field.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) SetOptionRebatePercent(v int32) {
	o.OptionRebatePercent = &v
}

// GetPerContractRebate returns the PerContractRebate field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) GetPerContractRebate() string {
	if o == nil || IsNil(o.PerContractRebate) {
		var ret string
		return ret
	}
	return *o.PerContractRebate
}

// GetPerContractRebateOk returns a tuple with the PerContractRebate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) GetPerContractRebateOk() (*string, bool) {
	if o == nil || IsNil(o.PerContractRebate) {
		return nil, false
	}
	return o.PerContractRebate, true
}

// HasPerContractRebate returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) HasPerContractRebate() bool {
	if o != nil && !IsNil(o.PerContractRebate) {
		return true
	}

	return false
}

// SetPerContractRebate gets a reference to the given string and assigns it to the PerContractRebate field.
func (o *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) SetPerContractRebate(v string) {
	o.PerContractRebate = &v
}

func (o ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EstimatedOptionRebate) {
		toSerialize["estimatedOptionRebate"] = o.EstimatedOptionRebate
	}
	if !IsNil(o.OptionRebatePercent) {
		toSerialize["optionRebatePercent"] = o.OptionRebatePercent
	}
	if !IsNil(o.PerContractRebate) {
		toSerialize["perContractRebate"] = o.PerContractRebate
	}
	return toSerialize, nil
}

type NullableComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate struct {
	value *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) Get() *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) Set(val *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate(val *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) *NullableComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate {
	return &NullableComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightGatewayOptionRebate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


