/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type Type of asset.
type ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type string

// List of com_hellopublic_userapigateway_api_rest_portfolio_GatewayPortfolioEquityV2_type
const (
	CASH ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type = "CASH"
	STOCK ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type = "STOCK"
	OPTIONS_LONG ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type = "OPTIONS_LONG"
	OPTIONS_SHORT ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type = "OPTIONS_SHORT"
	BONDS ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type = "BONDS"
	CRYPTO ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type = "CRYPTO"
)

// All allowed values of ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type enum
var AllowedComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2TypeEnumValues = []ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type{
	"CASH",
	"STOCK",
	"OPTIONS_LONG",
	"OPTIONS_SHORT",
	"BONDS",
	"CRYPTO",
}

func (v *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2TypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type", value)
}

// NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2TypeFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2TypeFromValue(v string) (*ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type, error) {
	ev := ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2TypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2TypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_portfolio_GatewayPortfolioEquityV2_type value
func (v ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type) Ptr() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type struct {
	value *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type) Get() *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type) Set(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type(val *ComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type) *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type {
	return &NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioGatewayPortfolioEquityV2Type) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

