/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg{}

// ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg Option or equity leg. There can never be more than 1 equity leg.
type ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg struct {
	Instrument ComHellopublicUserapigatewayApiRestOrderGatewayLegInstrument `json:"instrument"`
	Side ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide `json:"side"`
	OpenCloseIndicator *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator `json:"openCloseIndicator,omitempty"`
	// The ratio between legs. Equity legs will typically be 100 shares, and option legs 1 contract
	RatioQuantity *int32 `json:"ratioQuantity,omitempty"`
}

type _ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg

// NewComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg instantiates a new ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg(instrument ComHellopublicUserapigatewayApiRestOrderGatewayLegInstrument, side ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg {
	this := ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg{}
	this.Instrument = instrument
	this.Side = side
	return &this
}

// NewComHellopublicUserapigatewayApiRestOrderGatewayOrderLegWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestOrderGatewayOrderLegWithDefaults() *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg {
	this := ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg{}
	return &this
}

// GetInstrument returns the Instrument field value
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) GetInstrument() ComHellopublicUserapigatewayApiRestOrderGatewayLegInstrument {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestOrderGatewayLegInstrument
		return ret
	}

	return o.Instrument
}

// GetInstrumentOk returns a tuple with the Instrument field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) GetInstrumentOk() (*ComHellopublicUserapigatewayApiRestOrderGatewayLegInstrument, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instrument, true
}

// SetInstrument sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) SetInstrument(v ComHellopublicUserapigatewayApiRestOrderGatewayLegInstrument) {
	o.Instrument = v
}

// GetSide returns the Side field value
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) GetSide() ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide
		return ret
	}

	return o.Side
}

// GetSideOk returns a tuple with the Side field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) GetSideOk() (*ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Side, true
}

// SetSide sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) SetSide(v ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) {
	o.Side = v
}

// GetOpenCloseIndicator returns the OpenCloseIndicator field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) GetOpenCloseIndicator() ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator {
	if o == nil || IsNil(o.OpenCloseIndicator) {
		var ret ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator
		return ret
	}
	return *o.OpenCloseIndicator
}

// GetOpenCloseIndicatorOk returns a tuple with the OpenCloseIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) GetOpenCloseIndicatorOk() (*ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator, bool) {
	if o == nil || IsNil(o.OpenCloseIndicator) {
		return nil, false
	}
	return o.OpenCloseIndicator, true
}

// HasOpenCloseIndicator returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) HasOpenCloseIndicator() bool {
	if o != nil && !IsNil(o.OpenCloseIndicator) {
		return true
	}

	return false
}

// SetOpenCloseIndicator gets a reference to the given ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator and assigns it to the OpenCloseIndicator field.
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) SetOpenCloseIndicator(v ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegOpenCloseIndicator) {
	o.OpenCloseIndicator = &v
}

// GetRatioQuantity returns the RatioQuantity field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) GetRatioQuantity() int32 {
	if o == nil || IsNil(o.RatioQuantity) {
		var ret int32
		return ret
	}
	return *o.RatioQuantity
}

// GetRatioQuantityOk returns a tuple with the RatioQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) GetRatioQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.RatioQuantity) {
		return nil, false
	}
	return o.RatioQuantity, true
}

// HasRatioQuantity returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) HasRatioQuantity() bool {
	if o != nil && !IsNil(o.RatioQuantity) {
		return true
	}

	return false
}

// SetRatioQuantity gets a reference to the given int32 and assigns it to the RatioQuantity field.
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) SetRatioQuantity(v int32) {
	o.RatioQuantity = &v
}

func (o ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instrument"] = o.Instrument
	toSerialize["side"] = o.Side
	if !IsNil(o.OpenCloseIndicator) {
		toSerialize["openCloseIndicator"] = o.OpenCloseIndicator
	}
	if !IsNil(o.RatioQuantity) {
		toSerialize["ratioQuantity"] = o.RatioQuantity
	}
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instrument",
		"side",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg := _ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg(varComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg)

	return err
}

type NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg struct {
	value *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) Get() *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) Set(val *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg(val *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg {
	return &NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLeg) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


