/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
)

// checks if the ComHellopublicUserapigatewayApiRestAccountAccountSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestAccountAccountSettings{}

// ComHellopublicUserapigatewayApiRestAccountAccountSettings struct for ComHellopublicUserapigatewayApiRestAccountAccountSettings
type ComHellopublicUserapigatewayApiRestAccountAccountSettings struct {
	AccountId *string `json:"accountId,omitempty"`
	AccountType *string `json:"accountType,omitempty"`
	OptionsLevel *string `json:"optionsLevel,omitempty"`
	BrokerageAccountType *string `json:"brokerageAccountType,omitempty"`
	TradePermissions *string `json:"tradePermissions,omitempty"`
}

// NewComHellopublicUserapigatewayApiRestAccountAccountSettings instantiates a new ComHellopublicUserapigatewayApiRestAccountAccountSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestAccountAccountSettings() *ComHellopublicUserapigatewayApiRestAccountAccountSettings {
	this := ComHellopublicUserapigatewayApiRestAccountAccountSettings{}
	return &this
}

// NewComHellopublicUserapigatewayApiRestAccountAccountSettingsWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestAccountAccountSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestAccountAccountSettingsWithDefaults() *ComHellopublicUserapigatewayApiRestAccountAccountSettings {
	this := ComHellopublicUserapigatewayApiRestAccountAccountSettings{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) SetAccountId(v string) {
	o.AccountId = &v
}

// GetAccountType returns the AccountType field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) GetAccountType() string {
	if o == nil || IsNil(o.AccountType) {
		var ret string
		return ret
	}
	return *o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) GetAccountTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AccountType) {
		return nil, false
	}
	return o.AccountType, true
}

// HasAccountType returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) HasAccountType() bool {
	if o != nil && !IsNil(o.AccountType) {
		return true
	}

	return false
}

// SetAccountType gets a reference to the given string and assigns it to the AccountType field.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) SetAccountType(v string) {
	o.AccountType = &v
}

// GetOptionsLevel returns the OptionsLevel field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) GetOptionsLevel() string {
	if o == nil || IsNil(o.OptionsLevel) {
		var ret string
		return ret
	}
	return *o.OptionsLevel
}

// GetOptionsLevelOk returns a tuple with the OptionsLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) GetOptionsLevelOk() (*string, bool) {
	if o == nil || IsNil(o.OptionsLevel) {
		return nil, false
	}
	return o.OptionsLevel, true
}

// HasOptionsLevel returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) HasOptionsLevel() bool {
	if o != nil && !IsNil(o.OptionsLevel) {
		return true
	}

	return false
}

// SetOptionsLevel gets a reference to the given string and assigns it to the OptionsLevel field.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) SetOptionsLevel(v string) {
	o.OptionsLevel = &v
}

// GetBrokerageAccountType returns the BrokerageAccountType field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) GetBrokerageAccountType() string {
	if o == nil || IsNil(o.BrokerageAccountType) {
		var ret string
		return ret
	}
	return *o.BrokerageAccountType
}

// GetBrokerageAccountTypeOk returns a tuple with the BrokerageAccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) GetBrokerageAccountTypeOk() (*string, bool) {
	if o == nil || IsNil(o.BrokerageAccountType) {
		return nil, false
	}
	return o.BrokerageAccountType, true
}

// HasBrokerageAccountType returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) HasBrokerageAccountType() bool {
	if o != nil && !IsNil(o.BrokerageAccountType) {
		return true
	}

	return false
}

// SetBrokerageAccountType gets a reference to the given string and assigns it to the BrokerageAccountType field.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) SetBrokerageAccountType(v string) {
	o.BrokerageAccountType = &v
}

// GetTradePermissions returns the TradePermissions field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) GetTradePermissions() string {
	if o == nil || IsNil(o.TradePermissions) {
		var ret string
		return ret
	}
	return *o.TradePermissions
}

// GetTradePermissionsOk returns a tuple with the TradePermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) GetTradePermissionsOk() (*string, bool) {
	if o == nil || IsNil(o.TradePermissions) {
		return nil, false
	}
	return o.TradePermissions, true
}

// HasTradePermissions returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) HasTradePermissions() bool {
	if o != nil && !IsNil(o.TradePermissions) {
		return true
	}

	return false
}

// SetTradePermissions gets a reference to the given string and assigns it to the TradePermissions field.
func (o *ComHellopublicUserapigatewayApiRestAccountAccountSettings) SetTradePermissions(v string) {
	o.TradePermissions = &v
}

func (o ComHellopublicUserapigatewayApiRestAccountAccountSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestAccountAccountSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if !IsNil(o.AccountType) {
		toSerialize["accountType"] = o.AccountType
	}
	if !IsNil(o.OptionsLevel) {
		toSerialize["optionsLevel"] = o.OptionsLevel
	}
	if !IsNil(o.BrokerageAccountType) {
		toSerialize["brokerageAccountType"] = o.BrokerageAccountType
	}
	if !IsNil(o.TradePermissions) {
		toSerialize["tradePermissions"] = o.TradePermissions
	}
	return toSerialize, nil
}

type NullableComHellopublicUserapigatewayApiRestAccountAccountSettings struct {
	value *ComHellopublicUserapigatewayApiRestAccountAccountSettings
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestAccountAccountSettings) Get() *ComHellopublicUserapigatewayApiRestAccountAccountSettings {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestAccountAccountSettings) Set(val *ComHellopublicUserapigatewayApiRestAccountAccountSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestAccountAccountSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestAccountAccountSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestAccountAccountSettings(val *ComHellopublicUserapigatewayApiRestAccountAccountSettings) *NullableComHellopublicUserapigatewayApiRestAccountAccountSettings {
	return &NullableComHellopublicUserapigatewayApiRestAccountAccountSettings{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestAccountAccountSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestAccountAccountSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


