/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"fmt"
)

// ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide the model 'ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide'
type ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide string

// List of com_hellopublic_userapigateway_api_rest_order_GatewayOrderLeg_side
const (
	BUY ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide = "BUY"
	SELL ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide = "SELL"
)

// All allowed values of ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide enum
var AllowedComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSideEnumValues = []ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide{
	"BUY",
	"SELL",
}

func (v *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide(value)
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSideEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide", value)
}

// NewComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSideFromValue returns a pointer to a valid ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSideFromValue(v string) (*ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide, error) {
	ev := ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide: valid values are %v", v, AllowedComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSideEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) IsValid() bool {
	for _, existing := range AllowedComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSideEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to com_hellopublic_userapigateway_api_rest_order_GatewayOrderLeg_side value
func (v ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) Ptr() *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide {
	return &v
}

type NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide struct {
	value *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) Get() *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) Set(val *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide(val *ComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide {
	return &NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderLegSide) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

