/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse{}

// ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse # PreflightLegResponse Response containing information about an individual leg in a multi-leg order preflight calculation.  ## Fields  ### Instrument Information - **instrument** - The trading instrument for this leg - **side** - The order side (BUY/SELL) for this leg - **openCloseIndicator** - Position effect for option legs (BUY_TO_OPEN, BUY_TO_CLOSE, etc.) - **ratioQuantity** - The ratio quantity for this leg in the strategy  ### Cost and Fee Information - **estimatedCommission** - The estimated commission for this specific leg - **estimatedCost** - The estimated cost for this leg including fees - **estimatedProceeds** - The estimated proceeds for this leg (for sell legs)  ### Option-Specific Information - **optionDetails** - Option-specific details like strike price, expiration, fees, and rebates
type ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse struct {
	Instrument ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument `json:"instrument"`
	Side string `json:"side"`
	OpenCloseIndicator *string `json:"openCloseIndicator,omitempty"`
	RatioQuantity int32 `json:"ratioQuantity"`
	OptionDetails *ComHellopublicUserapigatewayApiRestPreflightGatewayOptionDetails `json:"optionDetails,omitempty"`
}

type _ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse

// NewComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse instantiates a new ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse(instrument ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument, side string, ratioQuantity int32) *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse {
	this := ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse{}
	this.Instrument = instrument
	this.Side = side
	this.RatioQuantity = ratioQuantity
	return &this
}

// NewComHellopublicUserapigatewayApiRestPreflightPreflightLegResponseWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPreflightPreflightLegResponseWithDefaults() *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse {
	this := ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse{}
	return &this
}

// GetInstrument returns the Instrument field value
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) GetInstrument() ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument {
	if o == nil {
		var ret ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument
		return ret
	}

	return o.Instrument
}

// GetInstrumentOk returns a tuple with the Instrument field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) GetInstrumentOk() (*ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instrument, true
}

// SetInstrument sets field value
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) SetInstrument(v ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) {
	o.Instrument = v
}

// GetSide returns the Side field value
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) GetSide() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Side
}

// GetSideOk returns a tuple with the Side field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) GetSideOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Side, true
}

// SetSide sets field value
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) SetSide(v string) {
	o.Side = v
}

// GetOpenCloseIndicator returns the OpenCloseIndicator field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) GetOpenCloseIndicator() string {
	if o == nil || IsNil(o.OpenCloseIndicator) {
		var ret string
		return ret
	}
	return *o.OpenCloseIndicator
}

// GetOpenCloseIndicatorOk returns a tuple with the OpenCloseIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) GetOpenCloseIndicatorOk() (*string, bool) {
	if o == nil || IsNil(o.OpenCloseIndicator) {
		return nil, false
	}
	return o.OpenCloseIndicator, true
}

// HasOpenCloseIndicator returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) HasOpenCloseIndicator() bool {
	if o != nil && !IsNil(o.OpenCloseIndicator) {
		return true
	}

	return false
}

// SetOpenCloseIndicator gets a reference to the given string and assigns it to the OpenCloseIndicator field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) SetOpenCloseIndicator(v string) {
	o.OpenCloseIndicator = &v
}

// GetRatioQuantity returns the RatioQuantity field value
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) GetRatioQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RatioQuantity
}

// GetRatioQuantityOk returns a tuple with the RatioQuantity field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) GetRatioQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RatioQuantity, true
}

// SetRatioQuantity sets field value
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) SetRatioQuantity(v int32) {
	o.RatioQuantity = v
}

// GetOptionDetails returns the OptionDetails field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) GetOptionDetails() ComHellopublicUserapigatewayApiRestPreflightGatewayOptionDetails {
	if o == nil || IsNil(o.OptionDetails) {
		var ret ComHellopublicUserapigatewayApiRestPreflightGatewayOptionDetails
		return ret
	}
	return *o.OptionDetails
}

// GetOptionDetailsOk returns a tuple with the OptionDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) GetOptionDetailsOk() (*ComHellopublicUserapigatewayApiRestPreflightGatewayOptionDetails, bool) {
	if o == nil || IsNil(o.OptionDetails) {
		return nil, false
	}
	return o.OptionDetails, true
}

// HasOptionDetails returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) HasOptionDetails() bool {
	if o != nil && !IsNil(o.OptionDetails) {
		return true
	}

	return false
}

// SetOptionDetails gets a reference to the given ComHellopublicUserapigatewayApiRestPreflightGatewayOptionDetails and assigns it to the OptionDetails field.
func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) SetOptionDetails(v ComHellopublicUserapigatewayApiRestPreflightGatewayOptionDetails) {
	o.OptionDetails = &v
}

func (o ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instrument"] = o.Instrument
	toSerialize["side"] = o.Side
	if !IsNil(o.OpenCloseIndicator) {
		toSerialize["openCloseIndicator"] = o.OpenCloseIndicator
	}
	toSerialize["ratioQuantity"] = o.RatioQuantity
	if !IsNil(o.OptionDetails) {
		toSerialize["optionDetails"] = o.OptionDetails
	}
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instrument",
		"side",
		"ratioQuantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse := _ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse(varComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse)

	return err
}

type NullableComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse struct {
	value *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) Get() *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) Set(val *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse(val *ComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) *NullableComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse {
	return &NullableComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPreflightPreflightLegResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


