/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"time"
)

// checks if the ComHellopublicUserapigatewayApiRestPortfolioPrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestPortfolioPrice{}

// ComHellopublicUserapigatewayApiRestPortfolioPrice struct for ComHellopublicUserapigatewayApiRestPortfolioPrice
type ComHellopublicUserapigatewayApiRestPortfolioPrice struct {
	LastPrice *string `json:"lastPrice,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// NewComHellopublicUserapigatewayApiRestPortfolioPrice instantiates a new ComHellopublicUserapigatewayApiRestPortfolioPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestPortfolioPrice() *ComHellopublicUserapigatewayApiRestPortfolioPrice {
	this := ComHellopublicUserapigatewayApiRestPortfolioPrice{}
	return &this
}

// NewComHellopublicUserapigatewayApiRestPortfolioPriceWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestPortfolioPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestPortfolioPriceWithDefaults() *ComHellopublicUserapigatewayApiRestPortfolioPrice {
	this := ComHellopublicUserapigatewayApiRestPortfolioPrice{}
	return &this
}

// GetLastPrice returns the LastPrice field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPortfolioPrice) GetLastPrice() string {
	if o == nil || IsNil(o.LastPrice) {
		var ret string
		return ret
	}
	return *o.LastPrice
}

// GetLastPriceOk returns a tuple with the LastPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioPrice) GetLastPriceOk() (*string, bool) {
	if o == nil || IsNil(o.LastPrice) {
		return nil, false
	}
	return o.LastPrice, true
}

// HasLastPrice returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioPrice) HasLastPrice() bool {
	if o != nil && !IsNil(o.LastPrice) {
		return true
	}

	return false
}

// SetLastPrice gets a reference to the given string and assigns it to the LastPrice field.
func (o *ComHellopublicUserapigatewayApiRestPortfolioPrice) SetLastPrice(v string) {
	o.LastPrice = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *ComHellopublicUserapigatewayApiRestPortfolioPrice) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioPrice) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ComHellopublicUserapigatewayApiRestPortfolioPrice) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *ComHellopublicUserapigatewayApiRestPortfolioPrice) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

func (o ComHellopublicUserapigatewayApiRestPortfolioPrice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestPortfolioPrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LastPrice) {
		toSerialize["lastPrice"] = o.LastPrice
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

type NullableComHellopublicUserapigatewayApiRestPortfolioPrice struct {
	value *ComHellopublicUserapigatewayApiRestPortfolioPrice
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioPrice) Get() *ComHellopublicUserapigatewayApiRestPortfolioPrice {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioPrice) Set(val *ComHellopublicUserapigatewayApiRestPortfolioPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestPortfolioPrice(val *ComHellopublicUserapigatewayApiRestPortfolioPrice) *NullableComHellopublicUserapigatewayApiRestPortfolioPrice {
	return &NullableComHellopublicUserapigatewayApiRestPortfolioPrice{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestPortfolioPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestPortfolioPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


