/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument{}

// ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument struct for ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument
type ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument struct {
	Symbol string `json:"symbol"`
	Type GetAllInstrumentsTypeFilterParameterInner `json:"type"`
}

type _ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument

// NewComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument instantiates a new ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument(symbol string, type_ GetAllInstrumentsTypeFilterParameterInner) *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument {
	this := ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument{}
	this.Symbol = symbol
	this.Type = type_
	return &this
}

// NewComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrumentWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrumentWithDefaults() *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument {
	this := ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument{}
	return &this
}

// GetSymbol returns the Symbol field value
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) SetSymbol(v string) {
	o.Symbol = v
}

// GetType returns the Type field value
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) GetType() GetAllInstrumentsTypeFilterParameterInner {
	if o == nil {
		var ret GetAllInstrumentsTypeFilterParameterInner
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) GetTypeOk() (*GetAllInstrumentsTypeFilterParameterInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) SetType(v GetAllInstrumentsTypeFilterParameterInner) {
	o.Type = v
}

func (o ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["symbol"] = o.Symbol
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"symbol",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument := _ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument(varComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument)

	return err
}

type NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument struct {
	value *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) Get() *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) Set(val *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument(val *ComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument {
	return &NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestOrderGatewayOrderInstrument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


