/*
User Api Gateway REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pubclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComHellopublicUserapigatewayApiRestUserPersonInfoName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComHellopublicUserapigatewayApiRestUserPersonInfoName{}

// ComHellopublicUserapigatewayApiRestUserPersonInfoName struct for ComHellopublicUserapigatewayApiRestUserPersonInfoName
type ComHellopublicUserapigatewayApiRestUserPersonInfoName struct {
	First string `json:"first"`
	Last string `json:"last"`
}

type _ComHellopublicUserapigatewayApiRestUserPersonInfoName ComHellopublicUserapigatewayApiRestUserPersonInfoName

// NewComHellopublicUserapigatewayApiRestUserPersonInfoName instantiates a new ComHellopublicUserapigatewayApiRestUserPersonInfoName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComHellopublicUserapigatewayApiRestUserPersonInfoName(first string, last string) *ComHellopublicUserapigatewayApiRestUserPersonInfoName {
	this := ComHellopublicUserapigatewayApiRestUserPersonInfoName{}
	this.First = first
	this.Last = last
	return &this
}

// NewComHellopublicUserapigatewayApiRestUserPersonInfoNameWithDefaults instantiates a new ComHellopublicUserapigatewayApiRestUserPersonInfoName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComHellopublicUserapigatewayApiRestUserPersonInfoNameWithDefaults() *ComHellopublicUserapigatewayApiRestUserPersonInfoName {
	this := ComHellopublicUserapigatewayApiRestUserPersonInfoName{}
	return &this
}

// GetFirst returns the First field value
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoName) GetFirst() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.First
}

// GetFirstOk returns a tuple with the First field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoName) GetFirstOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.First, true
}

// SetFirst sets field value
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoName) SetFirst(v string) {
	o.First = v
}

// GetLast returns the Last field value
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoName) GetLast() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Last
}

// GetLastOk returns a tuple with the Last field value
// and a boolean to check if the value has been set.
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoName) GetLastOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Last, true
}

// SetLast sets field value
func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoName) SetLast(v string) {
	o.Last = v
}

func (o ComHellopublicUserapigatewayApiRestUserPersonInfoName) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComHellopublicUserapigatewayApiRestUserPersonInfoName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first"] = o.First
	toSerialize["last"] = o.Last
	return toSerialize, nil
}

func (o *ComHellopublicUserapigatewayApiRestUserPersonInfoName) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first",
		"last",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComHellopublicUserapigatewayApiRestUserPersonInfoName := _ComHellopublicUserapigatewayApiRestUserPersonInfoName{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComHellopublicUserapigatewayApiRestUserPersonInfoName)

	if err != nil {
		return err
	}

	*o = ComHellopublicUserapigatewayApiRestUserPersonInfoName(varComHellopublicUserapigatewayApiRestUserPersonInfoName)

	return err
}

type NullableComHellopublicUserapigatewayApiRestUserPersonInfoName struct {
	value *ComHellopublicUserapigatewayApiRestUserPersonInfoName
	isSet bool
}

func (v NullableComHellopublicUserapigatewayApiRestUserPersonInfoName) Get() *ComHellopublicUserapigatewayApiRestUserPersonInfoName {
	return v.value
}

func (v *NullableComHellopublicUserapigatewayApiRestUserPersonInfoName) Set(val *ComHellopublicUserapigatewayApiRestUserPersonInfoName) {
	v.value = val
	v.isSet = true
}

func (v NullableComHellopublicUserapigatewayApiRestUserPersonInfoName) IsSet() bool {
	return v.isSet
}

func (v *NullableComHellopublicUserapigatewayApiRestUserPersonInfoName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComHellopublicUserapigatewayApiRestUserPersonInfoName(val *ComHellopublicUserapigatewayApiRestUserPersonInfoName) *NullableComHellopublicUserapigatewayApiRestUserPersonInfoName {
	return &NullableComHellopublicUserapigatewayApiRestUserPersonInfoName{value: val, isSet: true}
}

func (v NullableComHellopublicUserapigatewayApiRestUserPersonInfoName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComHellopublicUserapigatewayApiRestUserPersonInfoName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


